### ISSUE TITLE
Missing core/CompLibrary.js

### ISSUE THREAD

**Issue by shalevy1** [mingrammer/diagrams#10]

**Comment by totaloutput** [comment]
can you be more specific about the error? what is the steps?

**Comment by mingrammer** [comment]
what this is for?

**Comment by mingrammer** [comment]
I close this issue. Reopen later if needed.

**Comment by shalevy1** [comment]
Sorry for the late response, file  master/website/pages/en/index.js has the following line
const CompLibrary = require('../../core/CompLibrary.js');

The directory master/website/core does not have CompLibrary.js 

I am a JavaScript beginner so I maybe be missing the obvious :)

**Comment by mingrammer** [comment]
That is not a big issue :)
