### ISSUE TITLE
fix the spelling - typo - onprem = on premises - not premise

### ISSUE THREAD

**Issue by ibenrodriguez** [mingrammer/diagrams#1020]
please let's get the spelling correct for the english word premises - meaning onprem or on site. 

There should be no words spelled "premise" - it should end in an s or can be shortened to "onprem" 

Use this search to find all the incorrect spellings...

https://github.com/search?q=repo%3Amingrammer%2Fdiagrams%20premise&type=code

reference: https://www.grammarbook.com/blog/spelling/premise-or-premises/

Many people mix up “premise” and “premises,” but they mean different things. “Premise” is a statement or idea that forms the basis for a theory or argument. For example, if you say, “All humans need water to survive,” that’s a premise for discussing health and hydration. On the other hand, “premises” refers to a building or property. If your friend invites you over, they might say, “Please come to my premises.” So, remember: premise is about ideas, and premises is about physical spaces.

**Comment by filipeaaoliveira** [comment]
Hi @ibenrodriguez 

Thank you for pointing this out.
I'll take a look at it and come back to you.
