### ISSUE TITLE
Feature Request: Apigee icon

### ISSUE THREAD

**Issue by HariSekhon** [mingrammer/diagrams#1027]
This should probably go under SaaS or GCP.

Here is one I'm using from D2lang's icon set:

https://icons.terrastruct.com/gcp%2FProducts%20and%20services%2FAPI%20Management%2FApigee%20API%20Platform.svg

![](https://icons.terrastruct.com/gcp%2FProducts%20and%20services%2FAPI%20Management%2FApigee%20API%20Platform.svg)

**Comment by filipeaaoliveira** [comment]
Hi @HariSekhon 

I'll add this under GCP. 

Thank you providing the icon in the issue!

**Comment by filipeaaoliveira** [comment]
Hi @HariSekhon !

I believe we already have this: https://github.com/mingrammer/diagrams/blob/master/resources/gcp/api/apigee.png

Is this what you were looking for?

**Comment by HariSekhon** [comment]
That's probably sufficient as an icon although I didn't find `apigee` under either SaaS or GCP categories?

**Comment by filipeaaoliveira** [comment]
Hello @HariSekhon 

It's under GCP / API.

Did you have any particular error with this?

**Comment by filipeaaoliveira** [comment]
Hi @HariSekhon 
Were you able to find it? Can we close this issue?

**Comment by HariSekhon** [comment]
`diagrams.gcp.api.APIGateway` is a different product.

It looks like you haven't surfaced the Apigee icon in the library.

**Comment by filipeaaoliveira** [comment]
Hi @HariSekhon 

Sorry, I closed the issue.

You can import with `diagrams.gcp.api.Apigee`


Let me know if you run into any problems with this, and I'll reopen the issue!

**Comment by HariSekhon** [comment]
Ok that needs to be added to this page in that case:

https://diagrams.mingrammer.com/docs/nodes/gcp

**Comment by filipeaaoliveira** [comment]
Hello @HariSekhon 
You're right! Looks like it is not in the Docs. I'll use this issue to update the documentation on it!

**Comment by filipeaaoliveira** [comment]
Hello @HariSekhon 

You're right. Some issues are still not available in the last deployment of the documentation. I'll see if we can update this.

Thank you!

**Comment by filipeaaoliveira** [comment]
Hi @HariSekhon 

@mingrammer Just released a new version of the documentation, and you can see the icon available.

https://diagrams.mingrammer.com/docs/nodes/gcp


Let me know if I can close this issue.

Thank you for the patience on this!

**Comment by HariSekhon** [comment]
Thanks!
