### ISSUE TITLE
Feature Request : Next.JS as a framework and Vercel as a SasS service.

### ISSUE THREAD

**Issue by adityabhalsod** [mingrammer/diagrams#1033]
- [Next.Js](https://nextjs.org/) Popular react framework for the web development - https://iconduck.com/icons/94662/nextjs
- [Vercel](https://vercel.com/) Web deployment platform - https://iconduck.com/icons/1631/vercel

**Comment by adityabhalsod** [comment]
I guess for nextjs it's already created PR. - [#963](https://github.com/mingrammer/diagrams/pull/963)

**Comment by gabriel-tessier** [comment]
@adityabhalsod 
Thanks for the request and the link to the PR it help a lot.
