### ISSUE TITLE
Update gh-website with latest update

### ISSUE THREAD

**Issue by tvqphuoc01** [mingrammer/diagrams#1034]
Hi @mingrammer i think recently we have many update for new services from many source like AWS or Azure. But currently our current pipeline will not auto populate it to our website and docs. So i think we should populate this one. Or you can grant me, @gabriel-tessier, @filipeaaoliveira  permission to populate this one. The last time we deploy was Jan 13, 2023 -> https://github.com/mingrammer/diagrams/tree/gh-pages
FYI @gabriel-tessier @filipeaaoliveira 🚀

**Comment by mingrammer** [comment]
Hi! Yep, I'll update the websites and make the pipeline this weekend.

**Comment by mingrammer** [comment]
[v0.24.0](https://github.com/mingrammer/diagrams/releases/tag/v0.24.0) is now released, and the website is updated!

**Comment by tvqphuoc01** [comment]
Hi @mingrammer seems like the pipeline isn't auto-deploy our change after we create a new release [tag](https://github.com/mingrammer/diagrams/releases/tag/v0.24.2) 🤔
