### ISSUE TITLE
How to Caption Connector Arrows?

### ISSUE THREAD

**Issue by WilMorland** [mingrammer/diagrams#1054]
Hi,

I'm new to diagrams, and was wondering if it is possible to add a caption to a connector arrow?

![image](https://github.com/user-attachments/assets/8ac384f1-3fcd-4af2-9ead-d11924dc8618)

For instance, would it be possible to add a brief descriptor to the connector in the above image?

**Comment by adamk33n3r** [comment]
Add a manual `Edge(label="desc")` in between your nodes
