### ISSUE TITLE
Request for Crowdstrike icon

### ISSUE THREAD

**Issue by HariSekhon** [mingrammer/diagrams#1056]
Here is a good one:

https://cdn.prod.website-files.com/6640cd28f51f13175e577c05/664e007fb97281276484d675_110aeaaf-fe27-51ca-92fa-a7c426086de7.svg

![](https://cdn.prod.website-files.com/6640cd28f51f13175e577c05/664e007fb97281276484d675_110aeaaf-fe27-51ca-92fa-a7c426086de7.svg)

**Comment by mingrammer** [comment]
Could you please send a PR?
