### ISSUE TITLE
ImportError: No module named 'diagrams' (Ubunto 16.04 with python 2 and 3 installed)

### ISSUE THREAD

**Issue by oren** [mingrammer/diagrams#114]
Any idea how to solve this? I am not familiar with python so I apologize if this is trivial. 

pip install diagram
```
Defaulting to user installation because normal site-packages is not writeable
Collecting diagram
  Downloading diagram-0.2.28-py3-none-any.whl (13 kB)
Installing collected packages: diagram
Successfully installed diagram-0.2.28
```

python diagram.py
```
ImportError: No module named 'diagrams'
```

python3 diagram.py
```
ImportError: No module named 'diagrams'
```

python --version
```
Python 2.7.12
```

which python3
```
/usr/bin/python3
```

which python
```
/usr/bin/python
```
pip3 --version
```
pip 20.0.2 from /home/oren/.local/lib/python3.5/site-packages/pip (python 3.5)
```

**Comment by Ikki-Dai** [comment]
rename `diagram.py`
conflict between module name and your python script

**Comment by oren** [comment]
my script name is test.py and not diagrams.py and I see the same error. Sorry for the inaccuracy in my original post.

**Comment by mingrammer** [comment]
This library is `diagrams`, not `diagram`. `s` is missing there :)

**Comment by oren** [comment]
Got it. Now I see the following:

pip3 install diagrams
```
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement diagrams (from versions: none)
ERROR: No matching distribution found for diagrams
```

pip install diagrams
```
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement diagrams (from versions: none)
ERROR: No matching distribution found for diagrams
```

**Comment by oren** [comment]
this works: `sudo pip install diagrams`

but `python test.py`
```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from diagrams import Diagram
  File "/usr/local/lib/python2.7/dist-packages/diagrams/__init__.py", line 79
    name: str = "",
        ^
SyntaxError: invalid syntax
```

I assume the issue is I need to install it using pip3 but `sudo pip3 install diagrams`
```WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
WARNING: The directory '/home/oren/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
ERROR: Could not find a version that satisfies the requirement diagrams (from versions: none)
ERROR: No matching distribution found for diagrams
```

so this works: `sudo -H pip3 install diagrams'
but now `python3 test.py` give me:
```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from diagrams import Diagram
  File "/usr/local/lib/python3.5/dist-packages/diagrams/__init__.py", line 118
    raise ValueError(f'"{direction}" is not a valid direction')
                                                             ^
SyntaxError: invalid syntax
```

by the way, this is the content of test.py:
```
from diagrams import Diagram
from diagrams.aws.compute import EC2
from diagrams.aws.database import RDS
from diagrams.aws.network import ELB

with Diagram("Web Service", show=False):
    ELB("lb") >> EC2("web") >> RDS("userdb")
```

**Comment by mingrammer** [comment]
@oren Sorry for late reply.

> Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from diagrams import Diagram
  File "/usr/local/lib/python3.5/dist-packages/diagrams/__init__.py", line 118
    raise ValueError(f'"{direction}" is not a valid direction')
                                                             ^
SyntaxError: invalid syntax

This error occurs when your python version is less than Python 3.6. `f'"{direction}" is not a valid direction'` is formatted string literals which added since Python 3.6. Please update python version :)

p.s. I have to mention the required Python version in the README.md and website.

**Comment by oren** [comment]
now i have python3.7 (in addition to python2 and python 3.5).
how to install the the diagrams library? and tell pip i want to install it on my python 3.7?

**Comment by oren** [comment]
works now: 
```
sudo python3.7 -m pip install diagrams
```

Thank you!
