### ISSUE TITLE
Edges are joined incorrectly if two nodes point to another node

### ISSUE THREAD

**Issue by juv** [mingrammer/diagrams#117]
Hi,

I'm trying to visualize the following:

- One cluster of PostgreSQL Nodes
- Prometheus/Grafana Nodes
- pgAdmin Node
- pgAdmin points to each PostgreSQL node
- Prometheus points to each PostgreSQL node

```from diagrams import Cluster, Diagram
from diagrams.onprem.database import PostgreSQL
from diagrams.onprem.monitoring import Grafana, Prometheus

with Diagram("Edge Test", show=False):
	metrics = Prometheus("Prometheus")
	metrics << Grafana("Grafana")

	with Cluster("PostgreSQL"):
		db1 = PostgreSQL("db1") << metrics
		db2 = PostgreSQL("db2") << metrics
		db3 = PostgreSQL("db3") << metrics
		db4 = PostgreSQL("db4") << metrics
		db5 = PostgreSQL("db5") << metrics
		
	pgAdmin = PostgreSQL("pgAdmin")
	pgAdmin >> [db1,db2,db3,db4,db5] 
```

Output: 
![edge_test](https://user-images.githubusercontent.com/8269353/80827452-47b3ee00-8be4-11ea-8acc-5e88cfe84118.png)

I would have expected that pgAdmin node is for example on the left, pointing to each PostgreSQL node and that the Prometheus node is somewhere else but also shows its own edges to the PostgreSQL nodes. Is there something I am missing?

**Comment by mingrammer** [comment]
Hi.

It is because of the `db1 = PostgreSQL("db1") << metrics` returns `metrics`, not `PostgreSQL`. In this case, you can it this way:

```python
from diagrams import Diagram, Cluster
from diagrams.onprem.database import PostgreSQL
from diagrams.onprem.monitoring import Grafana, Prometheus

with Diagram("Edge Test", show=False):
    metrics = Prometheus("Prometheus")
    metrics << Grafana("Grafana")

    with Cluster("PostgreSQL"):
        db1 = PostgreSQL("db1")
        db2 = PostgreSQL("db2")
        db3 = PostgreSQL("db3")
        db4 = PostgreSQL("db4")
        db5 = PostgreSQL("db5")

    pgAdmin = PostgreSQL("pgAdmin")
    pgAdmin >> [db1, db2, db3, db4, db5] << metrics
```
