### ISSUE TITLE
re: Custom icons

### ISSUE THREAD

**Issue by bainss** [mingrammer/diagrams#119]
Hi,

Is it possible to define custom images to be defined?, I was trying to create diagrams with ou groups, users, and permissions.  

`  from diagrams.aws.management import ControlTower
  from diagrams.aws.management import Organizations
  from diagrams.aws.security import SingleSignOn
  from diagrams.aws.management import ServiceCatalog

  with Diagram("Landing Zone using Control Tower", show=True, direction="TB"):
      ct = ControlTower("Control Tower")
      sso = SingleSignOn("SSO")
      sc =  ServiceCatalog("Service Catalog")
      gr  = ServiceCatalog("Guard Rails")
      po = Organizations("AWS Organisation")

      with Cluster("SSO"):
          user_group = [SingleSignOn("Permissions") ,SingleSignOn("Users"),SingleSignOn("Groups")]`

Here I've had to use SingleSignOn for the Ou groups.

**Comment by mingrammer** [comment]
You can define a custom node with custom provider: https://diagrams.mingrammer.com/docs/getting-started/examples#rabbitmq-consumers-with-custom-nodes
