### ISSUE TITLE
How to change node color for OCI

### ISSUE THREAD

**Issue by mumanoha** [mingrammer/diagrams#120]
First of all, Thanks a lot for this amazing innovative tool!! Great work!!

I am new to this tool and still learning it, so please forgive me if I am wrong.

Based on my research, there is no way to change the color of the node / cloud resources icon, lets say for OCI, it's always black, but Oracle is Red. Is that something that you guys can provide a resolution?

Thanks in advance for the help / support!!

**Comment by mingrammer** [comment]
Hi. Thanks for your compliments.

First, there is no way to change the node color because all node is based on icon images. So node color depends on the color of icon image. And the OCI icons are grey colored.

But we can add the red-colored images so that able to use red node. Fortunately, there are red-colored icon image set: https://docs.cloud.oracle.com/en-us/iaas/Content/General/Reference/graphicsfordiagrams.htm

**Comment by mingrammer** [comment]
I'll support red-colored node.

**Comment by mingrammer** [comment]
Red-colored OCI nodes will be added to next version.

**Comment by mumanoha** [comment]
Thanks MinJae Kwon for your reply. Can you please let me know when next version will be available? 

 

I would like to change the color for the clusters like Tenancy, Compartment, VCN, OKE etc., Please refer below screenshots, 
Is that possible? If yes, can you pls guide me on that?

 

Output from Diagram tool:

 

 

Ideal output I would like to see:



 

-- 
Best regards, 

Muthu

**Comment by mingrammer** [comment]
Screenshot you attachted is not available to me. Could you please attach that in GitHub comment?

**Comment by mumanoha** [comment]
> Red-colored OCI nodes will be added to next version.

when this will be available? And how to use it? Please let me know.

**Comment by mingrammer** [comment]
Maybe tomorrow, I can release next version.

And there is no way to change the cluster background color yet. I should also work for it.

**Comment by mumanoha** [comment]
> Maybe tomorrow, I can release next version.
> 
> And there is no way to change the cluster background color yet. I should also work for it.

Can you please let me know whether the new version is ready? If yes, how to use it?

**Comment by mingrammer** [comment]
It's working hours now. Please wait until **May 06 at 21:00 KST** at least.

**Comment by mingrammer** [comment]
@mumanoha Diagrams v0.10.0 is now released.

**Comment by lucianf** [comment]
Just noticed this.

@mingrammer back in February I made a pull request (#46) that you accepted.  This introduced the then-current OCI icon set, which came in two colours, "bark" (a sort of dark brown) and white, which conformed to the new Oracle branding.  Now you've reverted to the red/white icon set - but this is an outdated one.  @mumanoha Oracle doesn't use red for OCI icons anymore.

I'm going to submit a new pull request with the latest icon set, again in bark and white (a slight variation of the February set).  Please stick to this going forward - this is the current Oracle branding which is to be used in all OCI diagrams.

**Comment by mingrammer** [comment]
@lucianf Hi! :)

I didn't know that the bark and white tones are the new branding icon set. Sorry for that :(. Yes, it would be good to revert it and keep the icon colors with the official new Oracle branding. @mumanoha Check it, please :)

**Comment by lucianf** [comment]
PR #205.  I've also added a few new services.  The icons are 256x256 scaled up from the official SVGs.

**Comment by mumanoha** [comment]
> Just noticed this.
> 
> @mingrammer back in February I made a pull request (#46) that you accepted. This introduced the then-current OCI icon set, which came in two colours, "bark" (a sort of dark brown) and white, which conformed to the new Oracle branding. Now you've reverted to the red/white icon set - but this is an outdated one. @mumanoha Oracle doesn't use red for OCI icons anymore.
> 
> I'm going to submit a new pull request with the latest icon set, again in bark and white (a slight variation of the February set). Please stick to this going forward - this is the current Oracle branding which is to be used in all OCI diagrams.

@lucianf I am with Oracle and I agree that we changed our branding color, but the red icons are still been used by many architecture diagrams both internally & externally. Is it possible to keep red icons and also bark & white icons to give that flexibility for end user to pick what color they prefer instead of removing the red color?

**Comment by lucianf** [comment]
@mumanoha sorry I don't agree - the branding has changed and going forward all Oracle materials is to be designed with the Redwood corporate theme.  The OCI old red/white icon set may be common, but it is now very much obsolete.
