### ISSUE TITLE
change the color for the clusters

### ISSUE THREAD

**Issue by mumanoha** [mingrammer/diagrams#122]
Hi Experts,

I would like to change the color for the clusters like Tenancy, Compartment, VCN, OKE etc., Please refer below screenshots,
Is that possible? If yes, can you pls guide me on that?

 **Output from Diagram tool:**

 <img width="619" alt="diagram-screenshot" src="https://user-images.githubusercontent.com/58404053/81076688-94801900-8eb1-11ea-87ab-459fccdd53c0.png">

**Ideal output I would like to see:**

![ideal_output](https://user-images.githubusercontent.com/58404053/81076749-a5c92580-8eb1-11ea-882a-95b36138c7d4.jpg)

**Comment by mingrammer** [comment]
As I mentioned [here](https://github.com/mingrammer/diagrams/issues/120#issuecomment-624171011), it is not supported yet. I’ll work for it, and it will be included in the next version along with red colored OCI icons.

**Comment by mingrammer** [comment]
Fixed via https://github.com/mingrammer/diagrams/commit/6741ed9e2bcca297a1044ca5c8f2cf9eb3f8b5b3

**Comment by mingrammer** [comment]
It will be release soon.

**Comment by mingrammer** [comment]
From Diagrams@0.10.0, you can pass the custom graph attributes to Cluster with this syntax:

```
with Cluster("PostgreSQL", graph_attr={"bgcolor": "#ddd"}):
        db1 = PostgreSQL("db1")
```

**Comment by mumanoha** [comment]
> From Diagrams@0.10.0, you can pass the custom graph attributes to Cluster with this syntax:
> 
> ```python
> with Cluster("PostgreSQL", graph_attr={"bgcolor": "#ddd"}):
>     db1 = PostgreSQL("db1")
> ```

I ran pip install diagrams again & I just tried this and I am getting below error, I think I am missing something here:

Traceback (most recent call last):
  File ".\future_state.py", line 118, in <module>
    with Cluster ("Primary Site", graph_attr={"bgcolor": "#ddd"}):
TypeError: __init__() got an unexpected keyword argument 'graph_attr'

**Comment by mingrammer** [comment]
What is your Diagrams version?

**Comment by mumanoha** [comment]
> What is your Diagrams version?

How to check?

**Comment by mingrammer** [comment]
`pip list` shows all installed packages with their versions.

**Comment by mumanoha** [comment]
> `pip list` shows all installed packages with their versions.

I see this: how do I update diagrams to latest version, I ran pip install diagrams as well,

Package    Version
---------- -------
diagrams   0.6.4
graphviz   0.13.2
Jinja2     2.11.1
MarkupSafe 1.1.1
pip        20.0.2

**Comment by mingrammer** [comment]
Your diagrams version is 0.6.4, please update with `pip install -U diagrams`.

**Comment by mumanoha** [comment]
> Your diagrams version is 0.6.4, please update with `pip install -U diagrams`.

Thanks!! now it's updated. I am seeing the icons in red now.

I tried graph_attr={"bgcolor": "#FFFFFF"}, it works as well for cluster. But I would like to have just the border line with some color but I want the fill color to be transparent, so that I can create something like below, is it possible?

![image](https://user-images.githubusercontent.com/58404053/81210933-3aa64e80-8f98-11ea-9e2b-a57a7c2e66fb.png)

**Comment by mingrammer** [comment]
Try with `pencolor` option:

```python
with Cluster("PostgreSQL", graph_attr={"pencolor": "#808080"}):
    db1 = PostgreSQL("db1")
```

**Comment by mumanoha** [comment]
> Try with `pencolor` option:
> 
> ```python
> with Cluster("PostgreSQL", graph_attr={"pencolor": "#808080"}):
>     db1 = PostgreSQL("db1")
> ```

Thanks, I will try that and will let you know.

**Comment by mumanoha** [comment]
> > Try with `pencolor` option:
> > ```python
> > with Cluster("PostgreSQL", graph_attr={"pencolor": "#808080"}):
> >     db1 = PostgreSQL("db1")
> > ```
> 
> Thanks, I will try that and will let you know.

It works really well!! Thanks a lot. You're awesome.

**Comment by mingrammer** [comment]
My pleasure.

**Comment by mumanoha** [comment]
> My pleasure.

Any ways to represent mobile devices, IOS, Android, Windows etc.,?

**Comment by mingrammer** [comment]
There are `onprem.client` nodes: https://diagrams.mingrammer.com/docs/nodes/onprem#onpremclient

But there are no platform-specific clients such as ios/android/windows yet.

**Comment by mumanoha** [comment]
> There are `onprem.client` nodes: https://diagrams.mingrammer.com/docs/nodes/onprem#onpremclient
> 
> But there are no platform-specific client nodes such as ios/android/windows yet.

Yes I used Client, but it's showing PC, but I want mobile as well. Any plans to include those in the future?
![image](https://user-images.githubusercontent.com/58404053/81428722-47ef4480-9122-11ea-9831-9a9988bbeed7.png)

**Comment by mingrammer** [comment]
Yes, I have a plan to support some generic nodes with `generic` provider. But I haven't set the exact date for that plan.

**Comment by mingrammer** [comment]
Could you please open the issue for this?

**Comment by ccamacho** [comment]
@mumanoha can you share an example of your diagram?
