### ISSUE TITLE
Colored flows

### ISSUE THREAD

**Issue by kevit** [mingrammer/diagrams#124]
Hi guys, extremely cool software, kudos!
Question, is it possible somehow to define colored flow? I would like to have particular end-to-end connections red, another green, I may define multiple Edge, but it destroys readability. Any suggestions here?

**Comment by mingrammer** [comment]
Yep. You can customize the connection with `Edge` component. Here is a link of reference documentation for the `Edge`: https://diagrams.mingrammer.com/docs/guides/edge

**Comment by kevit** [comment]
I know,  but the question is more about how to color line 
resource1 >> resource2 >> resource3 >> resource4

Now you are must create edge in each connection, which make much more noise if you need this connection be solid green 6

**Comment by mingrammer** [comment]
@kevit Sorry, I misread your question. In this case, you can make a helper function to add a colored for between multiple nodes in this way:

```python
from diagrams import Diagram, Cluster, Edge
from diagrams.aws.compute import EC2


def colored_flow(*nodes):
    for n1, n2 in zip(nodes, nodes[1:]):
        n1 >> Edge(color="orange") >> n2


with Diagram("diag", show=False):
    with Cluster("clst"):
        colored_flow(
            EC2("h1"),
            EC2("h2"),
            EC2("h3"),
            EC2("h4"),
        )
```

**Comment by mingrammer** [comment]
I close this issue :)
