### ISSUE TITLE
Support for generic icons

### ISSUE THREAD

**Issue by mumanoha** [mingrammer/diagrams#126]
Please provide support for generic icons like mobile, tablet, IOS, Android, Email, VMWARE, VBOX etc

**Comment by mlda065** [comment]
I'd like generic icons like a clock, to represent sleeping/waiting.

**Comment by leandrodamascena** [comment]
@mingrammer if you want I can do a PR to add this icons...

**Comment by mingrammer** [comment]
@leandrodamascena I’d appreciate it if you work for this :)

**Comment by leandrodamascena** [comment]
Ok ok... I think tomorrow it's done.

**Comment by mingrammer** [comment]
Thanks a lot!! :)

**Comment by leandrodamascena** [comment]
@mingrammer added new icons.

![image](https://user-images.githubusercontent.com/4295173/83688872-f41f3080-a5e5-11ea-83df-82161a20a88a.png)
