### ISSUE TITLE
Any reason why there's no customization available for Node like Edge?

### ISSUE THREAD

**Issue by ElvinEfendi** [mingrammer/diagrams#127]
[Looking at the source code](https://github.com/mingrammer/diagrams/blob/master/diagrams/__init__.py#L429), there's a way to customize `Edge` using `attrs` argument. Whereas for `Node` I can set only a label: https://github.com/mingrammer/diagrams/blob/353e7eb05153d2bed0823b3aee989f10847b58c6/diagrams/__init__.py#L270.

Any fundamental reason why is it not exposed? I'd be happy to make a PR request addressing this.

**Comment by mingrammer** [comment]
There is no big reason. Yes you can make PR for adding that.

**Comment by ElvinEfendi** [comment]
Thanks to @sulewicz this has now been addressed in https://github.com/mingrammer/diagrams/pull/151
