### ISSUE TITLE
Support for the Elastic Stack

### ISSUE THREAD

**Issue by morgango** [mingrammer/diagrams#134]
Where would you recommend putting icons for a SaaS service that runs on one of the major providers?  For example, Elastic has [Elastic Cloud](https://cloud.elastic.co) which can run on Google, Azure, Alibaba, or AWS.  

Thanks.

**Comment by mingrammer** [comment]
There are already some elastic services on `onprem` provider:

- es: https://diagrams.mingrammer.com/docs/nodes/onprem#onpremsearch
- kibana: https://diagrams.mingrammer.com/docs/nodes/onprem#onpremmonitoring
- logstash: https://diagrams.mingrammer.com/docs/nodes/onprem#onpremmonitoring

And we have a plan for adding the `saas` provider for some saas services. (maybe non-development software will be located to this provider)

Here is saas related issue: https://github.com/mingrammer/diagrams/issues/89

**Comment by gabriel-tessier** [comment]
I'll push a PR to add elastic as provider as discussed in the 168 PR (as I already have the resources).
It will make more sense to isolate elastic, this will prevent duplication with onprem as (nearly) all the service they provide can be saas or onprem.

**Comment by gabriel-tessier** [comment]
@mingrammer 

What about this issue?
As now there's an elastic provider can I remove the resources from onprem? 
but need to add a note in the readme as it will be a breaking change.

I can push a PR about.

**Comment by mingrammer** [comment]
It is currently supporting the elastic provider.
