### ISSUE TITLE
Add Openstack as cloud provider

### ISSUE THREAD

**Issue by chbndrhnns** [mingrammer/diagrams#15]
I would like to see an implementation of the Openstack ecosystem for drawing diagrams.

**Comment by mingrammer** [comment]
I'll support it in the near future.

**Comment by gabriel-tessier** [comment]
@mingrammer 

I searched for the set of icons for openstack and I already contact one person in the open stack project, he replied and sent a link to the resources. 
I can work on this one and push a PR this weekend, if it's ok for you.

**Comment by mingrammer** [comment]
@gabriel-tessier Great!! thank you for your efforts :) Yap, feel free to work for it!

**Comment by gabriel-tessier** [comment]
@chbndrhnns 
Hi, I pushed Open stack resourcs on a branch: https://github.com/gabriel-tessier/diagrams/tree/openstack

I used the following map for the categories:
https://object-storage-ca-ymq-1.vexxhost.net/swift/v1/6e4619c416ff4bd19e1c087f27a43eea/www-assets-prod/software/projectmap/openstack-map.pdf

and the icons from here: https://www.openstack.org/project-mascots/
I used the color one without the text.

If you have time to check before I push a PR, it will be helpful.

**Comment by mingrammer** [comment]
@gabriel-tessier Looks goood! Please send a PR :)
