### ISSUE TITLE
Partially initialized module 'diagrams' - circular import with Python 3.8.3

### ISSUE THREAD

**Issue by ViktorBarzin** [mingrammer/diagrams#175]
Hi there,

When I try to use the library (including the given examples) I get the following error once I try to
`from diagrams import Diagram`:

```
Traceback (most recent call last):
  File "diagrams.py", line 1, in <module>
    import diagrams
  File "/tmp/diagrams.py", line 10, in <module>
    with diagrams.Diagram("Web Service", show=False):
AttributeError: partially initialized module 'diagrams' has no attribute 'Diagram' (most likely due to a circular import)
```

My environment runs Python 3.8.3, `diagrams==0.12.0`, graphviz installed.

The simplest way to reproduce it is to open the python repl and run `from diagrams import Diagram`

**Comment by mingrammer** [comment]
Please use other filenames rather than diagrams.py. It could be conflicted with library name.

**Comment by ViktorBarzin** [comment]
Spot on, thanks!
tbf that was the only thing I didn't try :/

Have you thought of possible ways to prevent this naming issue from happening?
