### ISSUE TITLE
Docs improvement

### ISSUE THREAD

**Issue by EgorBu** [mingrammer/diagrams#178]
Hi,

Thanks for the really great work!
The only thing I'm struggling a bit - configuring different attributes of `Edge`s/`Cluster`s/etc. Some of them are not very intuitive ([example](https://github.com/mingrammer/diagrams/blob/master/diagrams/__init__.py#L60~L62)) - it would be really great if links to possible values of attributes with description will be provided (at least in code).

**Comment by clayms** [comment]
have a look at these answers:

https://github.com/mingrammer/diagrams/issues/306#issuecomment-722038830
https://github.com/mingrammer/diagrams/issues/243#issuecomment-721971788
https://github.com/mingrammer/diagrams/issues/202#issuecomment-722020465
https://github.com/mingrammer/diagrams/issues/364#issuecomment-719957643

**Comment by bdsoha** [comment]
@EgorBu Did the comments by @clayms help? If so, you can close this issue.

**Comment by EgorBu** [comment]
It was couple of years ago - I reacted positively - most probably it helped to solve the problem) thanks a lot! Closing the issue
