### ISSUE TITLE
Where to find the documentation?

### ISSUE THREAD

**Issue by aglpy** [mingrammer/diagrams#18]
I read the documentation but there is only examples, where to find the full documentation? I mean all available modules and icons?

Thanks

**Comment by mingrammer** [comment]
I’m working on it. It could be done in a day. Please wait :)

Thank you.

**Comment by mingrammer** [comment]
Hi! Here is nodes list documentation!

https://diagrams.mingrammer.com/docs/nodes/aws
https://diagrams.mingrammer.com/docs/nodes/azure
https://diagrams.mingrammer.com/docs/nodes/gcp
https://diagrams.mingrammer.com/docs/nodes/k8s

**Comment by mingrammer** [comment]
rel: #9

**Comment by mingrammer** [comment]
I close this issue. Reopen later if needed :)
