### ISSUE TITLE
Can't import Firebase

### ISSUE THREAD

**Issue by MatthieuLMR** [mingrammer/diagrams#184]
Hi !!

Sorry but i have a problem with Firebase.
When i generate diagram i can't import firebase

Message Error : 
File "~/.local/lib/python3.8/site-packages/diagrams/firebase/extentions.py", line 3, in <module>
    from . import _Firebase
ImportError: cannot import name '_Firebase' from 'diagrams.firebase' (unknown location)

I use Python3.8 on ubuntu 20.04

**Comment by mingrammer** [comment]
Sorry for the inconvenient. I fixed it and published a new version. Please update the Diagrams to v0.13.1.

**Comment by MatthieuLMR** [comment]
Thank's lot !!!
And thank's for this project !!
