### ISSUE TITLE
allow longer/descriptive labels on edges

### ISSUE THREAD

**Issue by hotzen** [mingrammer/diagrams#185]
when using labeled `Edge`s to document more complex behaviour like in the following
```
a  >> Edge(label="rather long label to describe what's going on") >> b
```

the edge is rendered very small and space-constrainted, the label is overlapped by cluster-borders and other nodes and is barely readable.

Is it possible to introduce another edge-parameter like `Edge(width=looooong)` or something?

Thanks a bunch for this tool!

**Comment by damnabit** [comment]
I see a few issues opened around spacing and I agree it would be nice to have the ability to have some control over the flow. A similar issue I'm having is that if I want to label two edges often the label text jumps and it's now over the wrong edge. Long labels, or 'padding', 'margins' something would help.

**Comment by clayms** [comment]
See if you can adapt the following:

```
with Diagram("\n\nLong Edge Labels", show=False) as diag:
    A = Node("", shape="circle")
    B = Node("", shape="star")
    C = Node("", shape="triangle")

    long_edge  = Edge(minlen="4", label="WOW!!!  this is a really long `Edge` label")
    short_edge = Edge(minlen="1", label="short label")

    A >> long_edge >> B >> short_edge >> C

diag
```

![image](https://user-images.githubusercontent.com/12793783/98247494-af574700-1f41-11eb-9731-2e68a944a1d1.png)


Also have a look at this answer.
https://github.com/mingrammer/diagrams/issues/364#issuecomment-719957643
