### ISSUE TITLE
Ability to remove title

### ISSUE THREAD

**Issue by andrew-waters** [mingrammer/diagrams#203]
👋  thanks for the awesome project. Is there any way to remove title from the generated images? I haven't been able to find anything in the docs or in issues.

**Comment by rieckpil** [comment]
for me `with Diagram("")` works

**Comment by andrew-waters** [comment]
Does it also work with `show=False`? I get a stack trace error under all circumstances

I'm iterating over many diagram sources, outputting them to a file relative to the source (which is a snake case of the `Diagram` name value (not my code, appears to be in this project) and then moving them in my project (a static site). To do that, I need to know the filename so I can move it. By not showing and instead writing, this workflow seems impossible, whilst excluding the name from the image itself.

**Comment by gabriel-tessier** [comment]
@andrew-waters 
You maybe already solve your problem but just in case, if you want to remove the title and save in a given name file you can use filename like this:

`with Diagram(filename="banana")`---> your diagram will not display any title and it will be saved in a file named Banana.png (as the png is the default render file).

for me `with Diagram("")` raise an error too.

Hope it help!

**Comment by andrew-waters** [comment]
@gabriel-tessier that's exactly what I needed, thank you - closing now ⭐
