### ISSUE TITLE
update to new version of OCI logos

### ISSUE THREAD

**Issue by cashfit** [mingrammer/diagrams#220]
hi,

I found that the resources are using old red/gray logos in OCI currently. 
Could you please update to the new black/white version of OCI logos?
https://docs.cloud.oracle.com/en-us/iaas/Content/Resources/Assets/OCI_Icons_EPS_PNG_SVG.zip

Thanks,
Eric

**Comment by mingrammer** [comment]
Resolved via #205. It will be updated in the next version.
