### ISSUE TITLE
Emoji on Edge labels

### ISSUE THREAD

**Issue by blacs30** [mingrammer/diagrams#221]
Is it possible to have emojis on the edge labels? I wasn't able to achieve it.

**Comment by clayms** [comment]
See https://graphviz.gitlab.io/doc/info/attrs.html#d:fontname

list your system fonts.  In Linux the command is `fc-list`

Then try:

```
with Diagram('\n\nemoji', show=False) as diag:
    Node(label="This is plain", shape="plaintext", fontname="Times bold")
    Node(label="🎉🎃", shape="plaintext", fontname="your-system-font-name-with-emojis")

diag
```

**Comment by blacs30** [comment]
Thanks a lot. That's working great.
