### ISSUE TITLE
Getting started link is dead

### ISSUE THREAD

**Issue by rgarrigue** [mingrammer/diagrams#23]
At least the one in the bottom of the website

**Comment by jbpratt78** [comment]
@rgarrigue [Here](https://diagrams.mingrammer.com/docs/getting-started/installation) is the link in case anyone else needs it! It seems that both links in the footer are leading to 404 due to the `en` rather than `getting-started`

**Comment by mingrammer** [comment]
I fixed all broken links in the footer.

Thank you for reporting :)
