### ISSUE TITLE
Add generic sql type

### ISSUE THREAD

**Issue by feluelle** [mingrammer/diagrams#232]
I am missing support for a generic sql type which could be in:
- provider: "generic"
- resource_type: "database"
- name: "sql"

WDYT?

**Comment by mingrammer** [comment]
Which is better between `generic.database.sql` or `generic.database.database`

**Comment by feluelle** [comment]
I am for `generic.database.sql` because I think one might want to display `generic.database.no-sql` ?!

**Comment by mingrammer** [comment]
Sounds reasonable. I added the generic SQL icon node. It will be included in the next version.

**Comment by mingrammer** [comment]
Diagrams v0.16.0 is now released with SQL, Druid and Databricks support.

![diag](https://user-images.githubusercontent.com/6178510/87320170-8e6b8000-c565-11ea-9c68-19de85e34b1c.png)
