### ISSUE TITLE
Cannot use OCI nodeset in diagrams>=0.16.0

### ISSUE THREAD

**Issue by marcolussetti** [mingrammer/diagrams#236]
Thank you for this delightful library!

---

Can't seem to import the oci nodeset:

```
from diagrams.oci.devops import Apiservice

ImportError: cannot import name 'Apiservice' from 'diagrams.oci.devops' (C:\Users\mlussetti\Anaconda3\lib\site-packages\diagrams\oci\devops.py)
```

This was from Python 3.7.4 on Windows via Anaconda & Jupyter Notebooks.

Tested:

- 0.13.0 :heavy_check_mark:
- 0.14.0 :heavy_check_mark:
- 0.15.0 :heavy_check_mark:
- 0.16.0 :x:

**Comment by gabriel-tessier** [comment]
Hi @marcolussetti 

The 0.16.0 introduce some change in the naming of the class for OCI provider.

please use :
`from diagrams.oci.devops import APIService`
instead of 
`from diagrams.oci.devops import Apiservice`

@mingrammer 
I can push a PR to update the migration file with the new paths.

**Comment by mingrammer** [comment]
Yes, some node classes for OCI was updated. (there is no breaking change log in the docs. Sorry for this)

@gabriel-tessier Does it mean to make the migration script? If so, sounds good.

**Comment by gabriel-tessier** [comment]
@mingrammer 
I thought about just update manually the migration file... 

I don't know if there's a need to make a script for this case. Class don't change between each version and here it's sound more like an edge case. 
Another solution is setting alias to keep compatibility with older versions but it will generate too much code and after that need to deprecate etc... too much maintenance.

If the class change too often It will be a pain for users to maintain their code between versions.
Except if in the Readme there's a disclaimer to explain that the class may change until version 1.x time to get main providers and fix all the TODO.

**Comment by mingrammer** [comment]
It was my mistake :(. I totally agree with you. The disclaimer is good option for us now. And after releasing the 1.0, we should version up the major version when the node class name is changed.

For now, we have to update the changelog with a breaking change table of old/new import paths like elasticsearch changes.

**Comment by gabriel-tessier** [comment]
@mingrammer 
I can push a PR with the changes this evening (UTC +9)

I will also check if there's other changes like this in previous version. I didn't check when I first updated the migration file.

**Comment by mingrammer** [comment]
@gabriel-tessier Thank you so much for your efforts :) From now on, I'll make a PR for some changes too and request reviews to you and @leandrodamascena.

**Comment by mingrammer** [comment]
I think we can close this issue. 

@marcolussetti Please check the breaking changed import paths for OCI provider in [here](https://github.com/mingrammer/diagrams/blob/master/CHANGELOG.md#oci) (thanks again @gabriel-tessier )

**Comment by marcolussetti** [comment]
Thanks, much appreciated!
