### ISSUE TITLE
Missing diagrams.generic documentation

### ISSUE THREAD

**Issue by huguesalary** [mingrammer/diagrams#258]
I noticed there's no link to https://diagrams.mingrammer.com/docs/nodes/generic anywhere on your website. Maybe that's on purpose, if not, now you know!

**Comment by huguesalary** [comment]
Actually, it's missing a few others, like "outscale"

**Comment by mingrammer** [comment]
I updated the website by adding missing providers (Generic, OutScale, and Openstack). Sorry for the inconvenient and thank you for reporting this issue :)

**Comment by huguesalary** [comment]
Great thanks!
