### ISSUE TITLE
Great
I think it is a great idea ,but you can make also add other clouds like amazon , tresorit etc . I think then it can be a hit .

But altogether it is GREAT🤐

### ISSUE THREAD

**Issue by IshaanDixit07** [mingrammer/diagrams#269]

**Comment by IshaanDixit07** [comment]
> 

Good

**Comment by steschuser** [comment]
Amazon is already in there, as seen in the guide: https://diagrams.mingrammer.com/docs/guides/cluster

**Comment by mingrammer** [comment]
If you can't find another cloud provider, please send us a PR for that :)

**Comment by IshaanDixit07** [comment]
> Amazon is already in there, as seen in the guide: https://diagrams.mingrammer.com/docs/guides/cluster

Ohh

**Comment by IshaanDixit07** [comment]
ok

**Comment by snash241** [comment]
All rights
