### ISSUE TITLE
Getting this error while running this in my Jupyter notebook CalledProcessError: Command '['dot', '-Tpng', '-O', 'simple_diagram']' returned non-zero exit status 1. [stderr: b'Format: "png" not recognized. Use one of:\r\n']

### ISSUE THREAD

**Issue by Nikhilkohli1** [mingrammer/diagrams#271]

**Comment by Nikhilkohli1** [comment]
Resolved. 

Apparently it was related to Graphviz installation in windows.  

Below are the steps which resolved this for me- 

if it is already installed through pip- 
pip uninstall graphiz 

conda install graphviz
conda install python-graphviz

**Comment by mledoze** [comment]
I got the same error on Windows 10 after installing graphviz with Scoop. This helped me: https://mamchenkov.net/wordpress/2019/01/15/graphviz-dot-format-png-not-recognized/

Simply run `dot -c` after the installation.
