### ISSUE TITLE
Feature Request - ability to pick up icons present in local path

### ISSUE THREAD

**Issue by manojlds** [mingrammer/diagrams#284]
It's going to be a never-ending process of adding new icons. Has there been talk of supporting custom icons, possibly taken from some local path via convention or configuration.

This will also allow us to use internal product icons in the diagrams as well.

**Comment by gabriel-tessier** [comment]
Hi @manojlds 

There's already a custom class check about in this issue: 
https://github.com/mingrammer/diagrams/issues/22

Look like there's no example in the doc.
@mingrammer 
I didn't found any reference to custom in the doc or example page if it's ok I can push a PR with an example.

**Comment by mingrammer** [comment]
There is already an example for the custom node: https://diagrams.mingrammer.com/docs/getting-started/examples#rabbitmq-consumers-with-custom-nodes

But it can be difficult to find as you have been. @gabriel-tessier It would be good to introduce the custom node in the `docs/guides/node` page too. Could you please push a PR for it?

**Comment by gabriel-tessier** [comment]
@mingrammer 

Ok, I'll give a try and push a PR this week.

**Comment by mingrammer** [comment]
Thank you! :)

**Comment by gabriel-tessier** [comment]
@mingrammer 
Long long week... finally I had time to check about and I'm not 100% sure about, but I generate a doc page now just linking to the example.
I made a "apidoc_custom.tmpl" file, here also not sure if it's the best way to go and also I didn't get how to see the generated result and how to format all the contents.
Just to confirm if I'm doing the things correctly.
If you can provide some direction it will be really helpful.
m(__)m

**Comment by wolfspyre** [comment]
ooh awesome! @mingrammer - @gabriel-tessier highlights a good point!

might it be informative / helpful for future collaborators / worth your time to use this opportunity to create a ‘how to doc new features’ guide ?

 “... help me help you ...” you know?

@gabriel-tessier - long week indeed, but it feels like 2020’s been full of those. nevertheless, thank you for helping out here!

MobileMail

**Comment by mingrammer** [comment]
@gabriel-tessier Thanks for the work :) But the `custom` provider can cause confusion to contributors because it is not an actual provider. Can you generate the custom docs page without adding it to the provider list?

**Comment by gabriel-tessier** [comment]
@wolfspyre 

> might it be informative / helpful for future collaborators / worth your time to use this opportunity to create a ‘how to doc new features’ guide ?

There's already an issue: https://github.com/mingrammer/diagrams/issues/108 and a PR https://github.com/mingrammer/diagrams/pull/109

This one was focusing on how to build and install your environment, I think the Docker push https://github.com/mingrammer/diagrams/pull/210 help to solve some installation problems.

So far what I did:
1. Adding icons: I think this one is fully documented and so far there's more than 50 different contributors that were able to do it, so I don't know if there's more to add.
2. Adding provider: This one may lack some documentation but I don't think it's really important as it's similar to add icons and strait forward, plus there's already several PR that can be checked to see where and what to change.
3. Making changes on website, here also there's documentation and it's not too complex only need to install npm and read how to write Markdown.

If you can provide more detail about where I can help (if I can) to make better doc. Better to open a new issue for this.

Sorry if I don't reply to your comment correctly or if I misunderstood.

**Comment by gabriel-tessier** [comment]
@mingrammer 
If there's nothing else to add here can you close it, please. 
I'll check if I can help working on another issue.

Thanks again for merging my PR.

m(__)m

**Comment by gabriel-tessier** [comment]
I think that everything is done here.
