### ISSUE TITLE
Cluster type (nesting) for resources like Network and VPC and similar

### ISSUE THREAD

**Issue by sokoow** [mingrammer/diagrams#287]
Hi All,

Would it be possible to do something like Cluster does for VPC?

I mean something like this:

```
from diagrams import Cluster, Diagram
from diagrams.gcp.network import VPC
from diagrams.gcp.compute import GKE

with Diagram("test", show=False, direction="LR"):

  with VPC("test VPC"):
      gke1 = GKE("test GKE")
```

So I'd love for things like VPC to behave like Cluster does, so draw an outline around items inside it, and display VPC icon in a corner somewhere. Unless this is already possible :)

**Comment by steschuser** [comment]
What would be the difference between using _with VPC_ and _with Cluster_ ?
If its just the icon, there is a pull request https://github.com/mingrammer/diagrams/pull/90 that would allow you to use the _with Cluster_ Option with a VPC Icon

**Comment by sokoow** [comment]
Yeah, that what I was exactly countring for - a cluster bevel with a small-ish vpc icon at one of its corners. Yay for this PR!  :D
