### ISSUE TITLE
add FastAPI

### ISSUE THREAD

**Issue by camerondavison** [mingrammer/diagrams#292]
Flask and Django exists, but I like the idea of also being able to specify FastAPI

![image](https://user-images.githubusercontent.com/165381/94048880-c844d800-fd99-11ea-8235-0b028bead515.png)

I think we could use just the lightning bolt part of the logo

**Comment by mingrammer** [comment]
Sounds good. Could you please send a PR for adding it?

**Comment by cryptoroo** [comment]
you can just add it is a a custom node?
