### ISSUE TITLE
Feature Request - diagrams.programming.language [COBOL, FORTRAN]

### ISSUE THREAD

**Issue by gmirsky** [mingrammer/diagrams#293]
Is it possible to add COBOL and FORTRAN to the diagrams.programming.language class? I'd suggest bash and powershell too but I don't want to go overboard. I'm containerizing a lot of legacy code hence the request.

It might even make more sense to have a generic programming language class that can be overloaded with a name and a icon.

**Comment by steschuser** [comment]
Bash is already included.
Do you have logos for Cobol, Fortran and Powershell?

**Comment by gmirsky** [comment]
Will these do?

![cobol](https://user-images.githubusercontent.com/6909025/94306329-c1a49500-ff40-11ea-89cf-ba00821648e9.png)
![powershell-logo](https://user-images.githubusercontent.com/6909025/94306337-c5381c00-ff40-11ea-99c9-ac30980dcc51.png)
![fortran](https://user-images.githubusercontent.com/6909025/94306340-c79a7600-ff40-11ea-897f-b752006730dc.png)

**Comment by mingrammer** [comment]
You can make a PR for adding these languages. You can find the contributing guide in [here](https://github.com/mingrammer/diagrams/blob/master/CONTRIBUTING.md).

**Comment by clayms** [comment]
In the meantime you can use `Custom()` nodes.

```
from diagrams import Cluster, Diagram
from diagrams.custom import Custom


with Diagram("\nCustom Nodes", show=False) as diag:
    cobol = Custom("Cobol", "cobol.png")
    pwsh = Custom("PowerShell", "pwsh.png")
    fortran = Custom("FORTRAN", "fortran.png")

    fortran >> cobol >> pwsh
 
diag
```

![image](https://user-images.githubusercontent.com/12793783/97117335-600b4e00-16d9-11eb-8f30-64e3835bc503.png)


image files used above:

![fortran](https://user-images.githubusercontent.com/12793783/97117346-74e7e180-16d9-11eb-9073-e29fc090b96f.png)

![cobol](https://user-images.githubusercontent.com/12793783/97117349-7b765900-16d9-11eb-8249-6e2f20dac2a0.png)

![pwsh](https://user-images.githubusercontent.com/12793783/97117353-7fa27680-16d9-11eb-9f07-547c156c69b4.png)

**Comment by gmirsky** [comment]
Excellent! Thank you. I have been hip deep in converting a bunch of legacy FORTRAN and COBOL programs from Windows to Linux and containerizing them to actually devote time to this. Last time I dealt with both programming languages was in 1987 so it has been a re-learning experience.
