### ISSUE TITLE
Kubernetes Support

### ISSUE THREAD

**Issue by jeyraof** [mingrammer/diagrams#3]
Do you have a plan to support Kubernetes layer?

I think that resources frequently refered on AWS contains `Ingress`, `Deployment`, `Service`, `StatefulSet` and so on.

Thank you.

**Comment by mingrammer** [comment]
Could you please show the example code (you want) for the Kubernetes layer? :)

**Comment by jeyraof** [comment]
Looks very ugly and tough, but I wish you could take my thought about this.

```python
from diagrams import Cluster, Diagram
from diagrams.k8s import Pod
from diagrams.k8s.apps.v1 import StatefulSet, Deployment, Ingress, Service
from diagrams.k8s.apps.v1.service import NodePort
from diagrams.aws.database import RDS, ElastiCache
from diagrams.aws.network import VPC
from diagrams.aws.integration import SQS


with VPC('Service Network'):
    authentication_db = RDS(name='authentication', type='aurora_posgresql')

    with Cluster('Database Cluster: Main'):
        main_db_master = RDS(name='main', type='aurora_mysql')
        main_db_master - [RDS(name='replicas')]

    with Cluster('Database Cluster: Auth'):
        auth_db_master = RDS(name='main', type='aurora_posgresql')
        auth_db_master - [RDS(name='replicas')]

    couchbase = StatefulSet(name='couchbase')

    with Cluster('Redis Cluster: cache'):
        cache_redis = [ElastiCache(name='cache_redis', type='redis'), ]

    with Cluster('Redis Clsuter: session'):
        session_redis = [ElastiCache(name='session_rdis', type='redis'), ]

    base_sqs = SQS(name='base')
    hard_sqs = SQS(name='hard')

    with Deployment('Deployment: api'):
        apis = [Pod(name='product1_api', port=3001), ]
        apis >> couchbase
        apis >> main_db_master
        apis >> auth_db_master
        apis >> cache_redis
        apis >> session_redis
        apis >> couchbase
        apis - base_sqs
        apis - hard_sqs

    with Deployment('Deployment: base_worker'):
        base_workers = [Pod(name='product1_worker_base'), ]
        base_workers >> main_db_master
        base_sqs - base_workers

    with Deployment('Deployment: hard_worker'):
        hard_workers = [Pod(name='product1_worker_hard'), ]
        hard_workers >> main_db_master
        hard_sqs - hard_workers

    # api
    ingress = Ingress(name='ingress')
    service = Service(name='product1_service', port=3000)
    ingress >> service >> NodePort(service_port=3000, target_port=3001) >> apis
```

Also, I think array of instances could be represented as stacked it:
```python
stacked = [Class(), ]
```

<img width="238" alt="image" src="https://user-images.githubusercontent.com/2032880/73811359-a0a9fb00-481c-11ea-9507-ec6ff0565640.png">
- Image from [here](https://www.outsystems.com/blog/posts/gestures_glamour_swipeable_stacked_cards/)

**Comment by mingrammer** [comment]
Thanks for the ideas.

All node classes of `diagrams` are based on resource icons provided by each provider (AWS, Azure, and GCP). Fortunately, k8s also provide the [icons set](https://docs.google.com/presentation/d/15h_MHjR2fzXIiGZniUdHok_FP07u1L8MAX5cN1r0j4U/edit#slide=id.g3375c55830_0_0).

However, there are some missing icons of specific resource types such as `NodePort`. (only `Service` exists). So I can support only a limited set of k8s resources listed in the above link. :(

And this code

```
from diagrams.k8s import Pod
from diagrams.k8s.apps.v1 import StatefulSet, Deployment, Ingress, Service
from diagrams.k8s.apps.v1.service import NodePort
```

should be like this, for keeping the consistency in classifiers for other providers.

```
from diagrams.k8s.compute import Pod, StatefulSet, Deployment
from diagrams.k8s.network import Ingress, Service
```

> In [icons set](https://docs.google.com/presentation/d/15h_MHjR2fzXIiGZniUdHok_FP07u1L8MAX5cN1r0j4U/edit#slide=id.g3375c55830_0_25), k8s team group the resources like this as well.

---

\+

Currently, `VPC` class is just a node class having `VPC` icon. (`Cluster` is the only way for grouping the nodes)

`diagrams` does not support grouping the resources with node classes except `Cluster` class. So this code does not work as you expected at least now. I need to check that this feature could be implemented with the current architecture.

```python
with VPC():
    pass

with Deployment():
    pass
```

---

\+

Graphviz does not support `stacked` diagram. But, It could be achived with some hacsk by making stacked icons for some (stackable) node icons). Let me think about support this feature.

**Comment by jeyraof** [comment]
Sounds good to me! 
If any curiosity or relative ideas you have,  please comment here.

**Comment by mingrammer** [comment]
Yap! Thank you :)

**Comment by mingrammer** [comment]
@jeyraof Diagrams v0.2.0 now supports basic Kubernetes diagrams!

## Node Types

```
diagrams/k8s
├── __init__.py
├── clusterconfig.py
├── compute.py
├── controlplane.py
├── group.py
├── infra.py
├── network.py
├── others.py
├── podconfig.py
├── rbac.py
└── storage.py
```

## Examples

```
# k8s resources
from diagrams.k8s.compute import Pod, StatefulSet
from diagrams.k8s.network import Service
from diagrams.k8s.storage import PV, PVC, StorageClass
...
```

* https://diagrams.mingrammer.com/docs/examples#exposed-pod-with-3-replicas-on-k8s
* https://diagrams.mingrammer.com/docs/examples#stateful-architecture-on-k8s

**Comment by jeyraof** [comment]
What a fast are you!
