### ISSUE TITLE
Feature Request - Discord Icon

### ISSUE THREAD

**Issue by FriendlyUser** [mingrammer/diagrams#311]
Similar to the slack icon I would like discord.

Something like diagrams.saas.chat.Discord

See https://discord.com/branding

**Comment by HIMANKARLIS** [comment]
@FriendlyUser I would like to help in your icon making

**Comment by FriendlyUser** [comment]
![Discord-Logo-Color](https://user-images.githubusercontent.com/13860264/94851306-2185ba80-03dd-11eb-8bd8-a52ec957779c.png)

I feel the standard blue icon would be enough, I am not sure how to add an icon, but would be eager to help in any way possible.

**Comment by FriendlyUser** [comment]
@HIMANKARLIS adding an icon looks to be pretty simple, I may go do it myself.

**Comment by HIMANKARLIS** [comment]
@FriendlyUser ok no problem 😊
