### ISSUE TITLE
Cloud Monitoring support in GCP

### ISSUE THREAD

**Issue by sann3** [mingrammer/diagrams#315]
Cloud Monitoring provides visibility into the performance, uptime, and overall health of cloud-powered applications.

https://cloud.google.com/monitoring

**Comment by clayms** [comment]
https://github.com/mingrammer/diagrams/blob/master/CONTRIBUTING.md#resources

**Comment by mingrammer** [comment]
Resolved by #343 . It will be added in the next version.
