### ISSUE TITLE
Newlines in labels result in padding issues

### ISSUE THREAD

**Issue by josegonzalez** [mingrammer/diagrams#32]
The following code:

```python
from diagrams import Diagram
from diagrams.aws.network import Route53 as DNS


with Diagram("Newline example", show=False):
    other_dns = DNS("One line DNS")
    newline_dns = DNS("Newline\nDNS")
```

Results in bad formatting for labels:

![newline_example](https://user-images.githubusercontent.com/65675/74964933-498e5380-53e2-11ea-842c-8e07b731e73a.png)

Not sure how I can properly push the label down. Looks fine for single line, but multi-line labels end up pretty bad.

---

Relevant debugging info:

```shell
$ python -V
Python 3.7.6
$ pip freeze | grep diagrams
diagrams==0.5.0
$ brew info graphviz
graphviz: stable 2.42.2 (bottled), HEAD
```

**Comment by mingrammer** [comment]
The label area has a fixed height, so multi-line text will be broken. Any reasons to use multi-line labels?

**Comment by josegonzalez** [comment]
I have some cases where the label is otherwise too long, so it goes over the cluster boundary.

**Comment by mingrammer** [comment]
@josegonzalez Diagrams v0.6.2 supports multi-line labels. Try with this version.

**Comment by josegonzalez** [comment]
Works great. Thanks!
