### ISSUE TITLE
Feature - add GCP IAP (Identity Aware Proxy) 

### ISSUE THREAD

**Issue by nareshgnT** [mingrammer/diagrams#33]
Please add GCP IAP (Identity Aware Proxy) Node.

**Comment by mingrammer** [comment]
There is no `IAP` icon in the official icons set: https://cloud.google.com/icons/

We should wait for google will add that icon.

**Comment by lkaybob** [comment]
Just a cacual suggestion. Since IAP utilizes Cloud IAM, how about using Cloud IAM icon?
(I guess it's `diagrams.gcp.security.Iam`?) @nareshgnT

**Comment by McSly** [comment]
The icon is available.
https://twitter.com/gcpcloud/status/907559417327079424
The main webpage for all the icons may not have updated yet.
I'll create a pull request
