### ISSUE TITLE
Add Browsers: Chrome, Safari, Firefox and etc

### ISSUE THREAD

**Issue by egorsmkv** [mingrammer/diagrams#334]
Like operation systems, but different browsers

**Comment by clayms** [comment]
You could add your own Resources.  See https://github.com/mingrammer/diagrams/blob/master/CONTRIBUTING.md#resources 

You could also use the `Custom` class of nodes with your own images.

```
from diagrams import Cluster, Diagram
from diagrams.custom import Custom

with Diagram("\nBrowsers", show=False) as diag:
    safari = Custom("Safari", "safari.png")
    edge = Custom("Edge", "edge.png")
    chrome = Custom("Chrome", "chrome.png")

    safari >> edge >> chrome
 
diag
```

![image](https://user-images.githubusercontent.com/12793783/97187372-c3988880-1778-11eb-9aba-04759fa8a771.png)

**Comment by egorsmkv** [comment]
Oh, haven’t seen this feature. Thanks!
