### ISSUE TITLE
Github Actions CI/CD?

### ISSUE THREAD

**Issue by marcellodesales** [mingrammer/diagrams#336]
Is there any diagram for Github Actions?

`diagrams.onprem.ci.Github`?

**Comment by mik-laj** [comment]
See: https://github.com/mingrammer/diagrams/pull/348

Should we close it?

**Comment by wolfspyre** [comment]
I might say that the merged PR #348 resolved this request. So that one didn’t have to click-through to see if this was a closed-wont-do-because-reasons, or a resolved-elsewhere :)

but yeah, seems like this is resolved
