### ISSUE TITLE
Inline show only (no file)

### ISSUE THREAD

**Issue by zifeo** [mingrammer/diagrams#36]
Great lib! It would be awesome to have more convenience when using `diagrams` in notebook (e.g. Jupyter). Is there a way of having no file saved and only showing inline (such as matplotlib)?

**Comment by mingrammer** [comment]
Isn’t `view=True` option working? (of course, this will save the file)

**Comment by zifeo** [comment]
Sadly not, it only opens a new window. How can this be overcome?

**Comment by mingrammer** [comment]
The `graphviz` library supoorts `_repr_svg_` for inline rendering in jupyter notebook. I'll also support it in `diagrams` in a day.

**Comment by mingrammer** [comment]
@zifeo Diagrams v0.6.3 now supports Inline rendering for jupyter notebook. Try with this version.

Guide reference: support inline rendering for jupyter notebook

**Comment by zifeo** [comment]
@mingrammer Fantastic, thanks!
