### ISSUE TITLE
Cluster nodes without connecting lines

### ISSUE THREAD

**Issue by pchaganti** [mingrammer/diagrams#37]
Is it possible to have a cluster of nodes where the nodes dont have any connecting lines?

thanks!

**Comment by mingrammer** [comment]
```python
with Cluster("No Connection"):
     Server("s1")
     Server("s2")
     Server("s3")
```

Isn't it working? Or do you mean other things?

**Comment by pchaganti** [comment]
That is exactly what I was looking for. Sorry I seem to have missed this in the examples.

thank you!
