### ISSUE TITLE
Feature Request: grouping

### ISSUE THREAD

**Issue by DataDecay** [mingrammer/diagrams#370]
It would be really awesome to be able to control grouping.

```
with Cluster("Compute"):
    compute_instances_set1 = [ComputeEngine(f"Instance {n+1}") for n in range(0, 10)]
    compute_instances_set1 = Group(compute_instances_set1, group_by=(2,5))
```

resulting in grouped mapping:

| Instance 1 |   | Instance 2 |   | Instance 3 |   | Instance 4 |   | Instance 5 |
| Instance 6 |   | Instance 7 |   | Instance 8 |   | Instance 9 |   | Instance 10 |

rather than linear mapping:
| Instance 1 |   | Instance 2 |   | Instance 3 |   | Instance 4 |   | Instance 5 | | Instance 6 |   | Instance 7 |   | Instance 8 |   | Instance 9 |   | Instance 10 |

**Comment by clayms** [comment]
@DataDecay 
Have a look at what I did here: https://github.com/mingrammer/diagrams/issues/290#issuecomment-719983090

**Comment by DataDecay** [comment]
That will do it! Thank you.
