### ISSUE TITLE
Feature Request: automatic label of node type

### ISSUE THREAD

**Issue by eugene-yao-zocdoc** [mingrammer/diagrams#376]
This is a great project! Thank you! 

I've build my first diagram and the first thing I notice is that you've got the correct and updated logos for the AWS components which actually makes comprehending a problem because most people are not familiar with the logos. I'm wondering if we can automate adding of the node type i.e. SQS, ECS, or Aurora to the node image somehow either above or below. 

Obviously as a workaround, I can add the type in my name of the node, but would be nice if this was included somehow automatically.

**Comment by anovis** [comment]
was thinking this as well.
