### ISSUE TITLE
Add Salesforce

### ISSUE THREAD

**Issue by robdyke** [mingrammer/diagrams#383]
Add Salesforce icon

**Comment by stanbiryukov** [comment]
You can create custom icons using `from diagrams.custom import Custom`
See: https://diagrams.mingrammer.com/docs/getting-started/examples#rabbitmq-consumers-with-custom-nodes

**Comment by robdyke** [comment]
Hey @stanbiryukov thanks for the note
@mingrammer What are the criteria for resources to be included in diagrams?

Related #363
