### ISSUE TITLE
Build out options to Custom

### ISSUE THREAD

**Issue by stanbiryukov** [mingrammer/diagrams#388]
Would be great if Custom had additional properties such as enabling resizing of the icon:

```
from diagrams.custom import Custom

Custom("Private\nEndpoint", icon_path=f"{parent_dir}/azPrivateEndpoint_logo.png")

# fails:
Custom("Private\nEndpoint", icon_path=f"{parent_dir}/azPrivateEndpoint_logo.png", width="0.5", height="0.8")

```

**Comment by clayms** [comment]
You can use the `Node` class directly and use all of the graphviz attributes.

**Comment by stanbiryukov** [comment]
So in this case I would make my own Node class for a custom image. I guess that's fine if we want to leave Custom as is.

**Comment by clayms** [comment]
You don't  have to make your own class it is already there.

See the following: 

https://github.com/mingrammer/diagrams/issues/306#issuecomment-722038830

https://github.com/mingrammer/diagrams/issues/243#issuecomment-721971788

https://github.com/mingrammer/diagrams/issues/202#issuecomment-722020465

**Comment by stanbiryukov** [comment]
Excellent, thanks @clayms - didn't fully grasp the utility of `Node`. 
The image argument is what I was after:
`Node(image=f"{parent_dir}/azPrivateEndpoint_logo.png",  width="0.5", height="0.8")`
