### ISSUE TITLE
Add Crawler to Aws Jobs

### ISSUE THREAD

**Issue by juanspinelli** [mingrammer/diagrams#4]
Could someone add the crawlers? This library is spectacular, I just need that item

**Comment by mingrammer** [comment]
Do you mean Glue Crawler?

**Comment by juanspinelli** [comment]
Yep https://docs.aws.amazon.com/glue/latest/dg/add-crawler.html

**Comment by mingrammer** [comment]
I'll add crawler support in a day!

On-premise service support is also a great idea. I'll support some popular services in a week!

**Comment by mingrammer** [comment]
Could you please give me some on-premise too list which would be nice to be supported.

I'm considering the mysql, postgresql, redis, memcached, elastic, kafka, nginx, docker, etc.

**Comment by mingrammer** [comment]
diagrams v0.2.1 is now released. (including `GlueCrawler` support)

**Comment by juanspinelli** [comment]
I was just thinking of an image that simulates an on premise, like a drawing of a server, but what you propose is a better idea, to detail the services, the ones you named seem perfect to me

**Comment by mingrammer** [comment]
I'll inform you when the on-premise service supports added!

And I close this issue :). You can use `GlueCrawler` in diagrams v0.2.1.
