### ISSUE TITLE
Labels for Nodes are overlapping

### ISSUE THREAD

**Issue by zmeghji** [mingrammer/diagrams#415]
The labels for the nodes are overlapping which makes them very difficult to read. Can I somehow change the sizes of the edges or do something else to separate the nodes enough?

![image](https://user-images.githubusercontent.com/2966373/102419873-bfe1ef00-3fce-11eb-991e-dacf12308c13.png)

**Comment by clayms** [comment]
See https://github.com/mingrammer/diagrams/issues/352#issuecomment-721985338

**Comment by zmeghji** [comment]
@clayms  Thank you. That's very helpful. I'll use Edge with minlen as a workaround. Closing this issue since it's a duplicate of #352
