### ISSUE TITLE
How to create custom class

### ISSUE THREAD

**Issue by monupurohit** [mingrammer/diagrams#417]
Need to create custom class
___________________________________________________
from diagrams.tcl.social import Hallow
____________________________________________________

#social.py

from . import _Saas

class _Social(_Saas):
    _type = "tcl"
    _icon_dir = "resources/tcl/social"

class Facebook(_Social):
    _icon = "facebook.png"

class Hallow(Facebook):
    _icon = "hallo.png"	

class Twitter(_Social):
    _icon = "twitter.png"
_______________________________________________________________________________

# Error code : 

Getting error : 
<ipython-input-74-cb5684bbe1a4> in <module>
----> 1 from diagrams.tcl.social import Hallow

ImportError: cannot import name 'Hallow' from 'diagrams.tcl.social' (C:\Users\mpurohit\Anaconda3\envs\tata\lib\site-packages\diagrams\tcl\social.py)

**Comment by gabriel-tessier** [comment]
@monupurohit 

What about the example from the documentation?

https://diagrams.mingrammer.com/docs/getting-started/examples#rabbitmq-consumers-with-custom-nodes

**Comment by mingrammer** [comment]
You can find how to make custom nodes in documentation as @gabriel-tessier did mention above.
