### ISSUE TITLE
Edge labels at both ends

### ISSUE THREAD

**Issue by cldeluna** [mingrammer/diagrams#427]
Hi,

First thank you for this module!  My first learning exercise of the new year was to try using your diagrams module to map out a network topology.   I've gotten further with *diagrams* than with dot, Graphviz, networkx, etc.  I'd like to add labels at the start and end of each edge (representing interface numbers).  In a perfect world I'd like to have labels at the start, middle, and end of some Edges.   Is that possible?  

Thanks again and Happy 2021!

**Comment by clayms** [comment]
@cldeluna 
You can set the `headlabel` and `taillabel` `Edge` parameters.

See: 
https://graphviz.gitlab.io/doc/info/attrs.html#d:taillabel
https://graphviz.gitlab.io/doc/info/attrs.html#d:headlabel
and see limitations: https://graphviz.gitlab.io/doc/info/attrs.html#h:undir_note

https://graphviz.gitlab.io/doc/info/attrs.html#d:label
https://graphviz.gitlab.io/doc/info/attrs.html#d:xlabel

Example:

```python
from diagrams import Diagram, Edge, Node

with Diagram("\n\nEdge labels", show=False) as diag:
    tail_node = Node("tail", shape="cds", labelloc="c")
    head_node = Node("head", shape="star", labelloc="c")
    
    (
        tail_node >> 
        Edge(
            minlen="5", 
            label="above the\nEdge\n\n",
            xlabel="\nunder the\nEdge",
            labelloc="t",
            taillabel="Edge\ntail", 
            headlabel="Edge\nhead",
            labelangle="0",
            labeldistance="4",
        ) >> 
        head_node
    )

diag
```

![image](https://user-images.githubusercontent.com/12793783/103459531-227cff80-4cde-11eb-9d47-d0256e13bbb5.png)

**Comment by cldeluna** [comment]
@clayms thank you for such an excellent detailed answer!
