### ISSUE TITLE
Allow nodes to have edges that reference themselves

### ISSUE THREAD

**Issue by ashleyconnor** [mingrammer/diagrams#432]
I'm looking at using `diagrams` to produce network diagrams for AWS Security Groups and one of the requirements is that a Security Group can reference itself to allow inbound and outbound traffic on a certain port.

I'm looking a producing a node that can have edges that look something like [this](http://www.gravizo.com/svg?digraph%20finite_state_machine%20%7B%20%20rankdir=LR;%20%20size=%228,2%22%20%20fontname=%22Verdana%22%20%20node%20[shape%20=%20doublecircle];%20Idle;%20%20node%20[shape%20=%20circle,nodesep%20=%20%222.0%22];%20%20Working:s%20-%3E%20Working:s%20[%20label%20=%20%22response[j]?%22%20,minlen%20=%2050000];%20%20Idle%20-%3E%20Working%20[%20label%20=%20%22boot%22%20];%20%20Working:n%20-%3E%20Working:n%20[%20label%20=%20%22sendtx[i]%22];%20%20Working:e%20-%3E%20Working:e%20[%20label%20=%20%22qry%22%20];%20%20nodesep=0.7;%7D).

**Comment by clayms** [comment]
You just need to change the `graph_attr` dictionary key `"splines"` to the value `"spline"` (default in this library is `"ortho"`).

Then specify the `headport` and `tailport` of the self-referring `Edge`s.

```python
from diagrams import Diagram, Node, Edge

graph_attr = {
    "splines": "spline",
}

with Diagram('',show=False, graph_attr=graph_attr) as diag:
    idle = Node('Idle', shape="doublecircle", labelloc="c",)
    working = Node('Working', shape="circle", labelloc="c",)

    idle >> Edge(label="boot",) >> working

    working >> Edge(label="sendtx[i]", tailport="n", headport="n") >> working
    working >> Edge(label="qry", tailport="e", headport="e") >> working
    working >> Edge(label="response[j]", tailport="s", headport="s") >> working

diag
```

![image](https://user-images.githubusercontent.com/12793783/103936304-3fa63980-50f5-11eb-9b64-02d007e00b1c.png)


Ref:
https://graphviz.gitlab.io/doc/info/attrs.html#d:headport
https://graphviz.gitlab.io/doc/info/attrs.html#d:tailport
https://graphviz.gitlab.io/doc/info/attrs.html#k:portPos

**Comment by ashleyconnor** [comment]
This worked!

Thank you for the quick answer and creating such an awesome project.
