### ISSUE TITLE
How to Create TextBox or Legend

### ISSUE THREAD

**Issue by crhuber** [mingrammer/diagrams#447]
I would like to include some notes on my diagram with some basic text. How would i create a textbox for a legend?

ie:

```
  legend:
  eks = amazon elastic kubernetes service 
  rds = amazon relational database service 
  vpc = amazon virtual private network"
```

**Comment by crhuber** [comment]
I tried doing this

```
from diagrams import Diagram
from diagrams.custom import Custom

with Diagram("\nCustom", show=False) as diag:
    Custom_1 = Custom("My\nCustom\ntext #1\n\n\nHELLO", "")
    Custom_2 = Custom("My 2nd\nCustom\nstring\n\n\nWORLD!", "")
```
but when i have long text it doesnt fit inside the box

**Comment by clayms** [comment]
Have a look at these comments:

https://github.com/mingrammer/diagrams/issues/202#issuecomment-722020465
https://github.com/mingrammer/diagrams/issues/389#issuecomment-737537465
https://github.com/mingrammer/diagrams/issues/290#issuecomment-720159611

**Comment by clayms** [comment]
example code:

Note the use of `"\l"`  to left-justify the `Node` label.
See http://www.graphviz.org/doc/info/attrs.html#k:escString 

```python
from diagrams import Diagram, Node

diagram_label = ("\n"
    "Use a Plain Text Node as Diagram Legend"
)

legend_text = (
"legend: \l"
"eks = amazon elastic kubernetes service \l"
"rds = amazon relational database service \l"
"vpc = amazon virtual private network \l"
)

with Diagram(diagram_label, show=False) as diag:
    Node(label=legend_text, width="8", shape="plaintext", )

diag
```

![image](https://user-images.githubusercontent.com/12793783/106394541-12cf0480-63cb-11eb-9422-c1cf77d18969.png)

**Comment by crhuber** [comment]
@clayms great thanks! Would be great to have this as a high level object to use to make it easier. I'll close this for now thanks!

**Comment by scottstirling** [comment]
@clayms Very handy tip, thank you!

**Comment by gshiva** [comment]
You can fix this by adding a `r` to the beginning of each string.

```python
legend_text = (
r"legend: \l"
r"eks = amazon elastic kubernetes service \l"
r"rds = amazon relational database service \l"
r"vpc = amazon virtual private network \l"
)
```
