### ISSUE TITLE
Add SSM Parameter Store

### ISSUE THREAD

**Issue by ehammond** [mingrammer/diagrams#45]
Please consider adding an icon for (AWS) SSM Parameter Store.

**Comment by mingrammer** [comment]
Diagrams v0.6.4 is now released with AWS management resources support.

Check out docs: https://diagrams.mingrammer.com/docs/nodes/aws#awsmanagement

**Comment by josegonzalez** [comment]
This can be closed I think?

**Comment by mingrammer** [comment]
We can close it.
