### ISSUE TITLE
Reduce whitespace at the top images

### ISSUE THREAD

**Issue by foolish-dev** [mingrammer/diagrams#459]
As you can see from the attached image, all generated images have a big amount of whitespace at the top and bottom, with the one at the top being the most problematic, especially when used via Jupyter Notebooks. 

- [ ] reduce whitespace for generated images
- [ ] add option for image size/dimensions 

<img width="657" alt="CleanShot 2021-02-06 at 10 16 57@2x" src="https://user-images.githubusercontent.com/61799047/107129713-37d9e080-68bf-11eb-81f0-d69dbc23b40c.png">

**Comment by clayms** [comment]
Simply set the `"margin"`  key of the `graph_attr` dictionary to a negative value.  You can set the x and y margins separately.

See: https://graphviz.gitlab.io/doc/info/attrs.html#d:margin

Example code below:
(Note: the black border is the edge of the Jupyter notebook cell.)

```

from diagrams import Diagram, Cluster, Node

graph_attr = {
    "bgcolor": "cornflowerblue",
    "margin":"-2, -2"
}

with Diagram("background", graph_attr=graph_attr, show=False) as diag:
    a = Node(shape="triangle")
    b = Node(shape="star")
    c = Node(shape="diamond")
    
    a >> b >> c

diag
```

![image](https://user-images.githubusercontent.com/12793783/107132035-c2174a00-68a9-11eb-8335-b9a83efb98f5.png)


Without the margin, or set to "0" , which is the same as not setting it at all:
```
...
    "margin":"0"
...
```

![image](https://user-images.githubusercontent.com/12793783/107132067-099dd600-68aa-11eb-9600-a292cf793363.png)

**Comment by foolish-dev** [comment]
Yes this works perfectly. Thank you 👍

**Comment by couling** [comment]
>     graph_attr = {
>         "bgcolor": "cornflowerblue",
>         "margin":"-2, -2"
>     }

Something really smells when you have to set a negative margin.  Playing around a bit it's definitely possible to make this erroneously cut off part of your diagram.  

I think the white space is originating from the [pad](https://www.graphviz.org/docs/attrs/pad/) setting.

All "white space" disapperas when I use:

     graph_attr = {
         "pad":"0"
     }

Setting something to 0 to trim seems much safer than setting an arbitrary "-2".
