### ISSUE TITLE
Organize Nodes by Columns/Lines in a Cluster, is it possible ?  

### ISSUE THREAD

**Issue by ualter** [mingrammer/diagrams#464]
Is that a way to define a number of columns/lines in a Cluster?   

For example, if I have a Cluster of 30 EC2 Instances, I would like to create a Cluster with 5 Lines by 6 Columns, this way we have a more "readable" diagram, not a very large width graph (not really useful).

**Comment by clayms** [comment]
You'll have to implement something yourself.

The following is an example is one way of doing that.  
https://github.com/mingrammer/diagrams/issues/290#issuecomment-719983090 

Of course there are many others.

**Comment by ualter** [comment]
> You'll have to implement something yourself.
> 
> The following is an example is one way of doing that.
> [#290 (comment)](https://github.com/mingrammer/diagrams/issues/290#issuecomment-719983090)
> 
> Of course there are many others.

Great! Thanks!

**Comment by clayms** [comment]
You could also use the `neato` layout engine and set the exact x,y position of each Node.

See: https://github.com/mingrammer/diagrams/issues/243#issuecomment-721971788
