### ISSUE TITLE
Release latest version on PyPi

### ISSUE THREAD

**Issue by arihantsurana** [mingrammer/diagrams#469]
I have noticed that the current master has many new changes, like flowchart in the programming module. These are not available in the PyPi registry, as the latest artifact there is from Dec 4, 2020.
Please publish a newer version.

![image](https://user-images.githubusercontent.com/21052816/108651940-f54b1180-7516-11eb-8cb7-314d326abcd4.png)

**Comment by mingrammer** [comment]
v0.19.0 is now released. Thanks.
