### ISSUE TITLE
Support for the port numbers for incoming/outgoing connections in diagrams

### ISSUE THREAD

**Issue by yetis200** [mingrammer/diagrams#483]
Hi All,

It will be very useful to include port numbers in diagrams for incoming and outgoing connections. 
Attached is the screenshot capture.png
![Capture](https://user-images.githubusercontent.com/23635692/110234955-4fa29400-7f53-11eb-999b-56ac578ea45d.PNG)

Image Source - Google

**Comment by clayms** [comment]
Use `Edge` labels.

Example:


```
from diagrams import Diagram, Edge, Node

with Diagram("edge labels", show=False) as diag:
    (
        Node(shape="triangle") >> 
        Edge(minlen="4", label="100.100.100.111") >> 
        Node(shape="star")
    )

diag
```


![image](https://user-images.githubusercontent.com/12793783/110337614-1e2dd500-7ff4-11eb-888b-5a4233570e48.png)

see the following for more `Edge` label options:

[label](https://graphviz.gitlab.io/doc/info/attrs.html#d:label)
[labelangle](https://graphviz.gitlab.io/doc/info/attrs.html#d:labelangle)
[labeldistance](https://graphviz.gitlab.io/doc/info/attrs.html#d:labeldistance)
[labelfloat](https://graphviz.gitlab.io/doc/info/attrs.html#d:labelfloat)
[labelfontcolor](https://graphviz.gitlab.io/doc/info/attrs.html#d:labelfontcolor)
[labelfontname](https://graphviz.gitlab.io/doc/info/attrs.html#d:labelfontname)
[labelfontsize](https://graphviz.gitlab.io/doc/info/attrs.html#d:labelfontsize)
[xlabel](https://graphviz.gitlab.io/doc/info/attrs.html#d:xlabel)


Also see this issue comment:
https://github.com/mingrammer/diagrams/issues/389#issuecomment-737537465
