### ISSUE TITLE
Developers or Users missing functions

### ISSUE THREAD

**Issue by kenichi-shibata** [mingrammer/diagrams#484]
HI I wanted to give this a whirl but all my diagrams are anchored with a developer or enduser and i cant find any functions to use to create them. 

Also is there a legend function i can use? for like coloring arrows or boxes etc...

Thanks :) Keep up the good work :D

**Comment by clayms** [comment]
@kenichi-shibata I don't follow.  What do you mean "anchored with a ... " ?

Please post your code.

You can color arrows and boxes any color listed in the [Graphviz docs](https://graphviz.gitlab.io/doc/info/colors.html).   
However, you will have to create your own legend.  

See this issue comment: https://github.com/mingrammer/diagrams/issues/447#issuecomment-770430158

**Comment by clayms** [comment]
@kenichi-shibata 
> sorry i just mean if we have a user and a developer function we can use,  

Sorry, I still don't follow.  How would you define a "user" function differently than a "developer" function?  

Do you mean you are looking for two separate functions or methods in this library that different people could use depending on their role in your company?

**Comment by kenichi-shibata** [comment]
> Sorry, I still don't follow. How would you define a "user" function differently than a "developer" function?

User = End User / Customer 
Developer -> github mostly what im looking for.

It doesnt have to be two separate ones it can be the same with different annotations.

**Comment by clayms** [comment]
@kenichi-shibata   I was not asking for a definition of a user and developer, I was asking you to define the how you want the ***functions*** to be different for each.

It would be much easier if you posted some example code and explain what you are expecting or would like from each example.

**Comment by kenichi-shibata** [comment]
example diagrams 

![Blank diagram](https://user-images.githubusercontent.com/13744098/111973481-708feb00-8af6-11eb-804b-429e25948314.png)

example code 1
```
from diagrams import Diagram
from diagrams.aws.compute import EC2
from diagrams.aws.database import RDS
from diagrams.aws.network import ELB
from diagrams.generic.actor import SingleUser

with Diagram("Web Service", show=False):
    SingleUser("EndUser") >> ELB("lb") >> EC2("web") >> RDS("userdb")


```

example code 2

```
from diagrams import Diagram
from diagrams.generic.actor import MultiUser
from diagrams.saas.scm.github import Repo, Actions
from diagrams.generic.text import TextBox

with Diagram("Do Nothing", show=False):
    MultiUser("Developers") >> Repo("") >> Actions("") >> TextBox("Do Something", box="None")

```

Or something like that

**Comment by clayms** [comment]
How do you want the diagram creation "functions" to be "annotated" differently depending on whether the "functions" are "anchored" with a developer (Software devs) or enduser (User / Customer) ?

Is `example code 1` what generates the diagram that is "anchored" with a developer?
Is `example code 2` what generates the diagram that is "anchored" with a enduser?


You want a python function to generate either a "user" diagram or "developer" depending on a function parameter you can change.  
If I understand you correctly, creating this function is totally on you.  I don't see how this could or should be added to this library as it sounds very specific to you.

**Comment by kenichi-shibata** [comment]
> If I understand you correctly, creating this function is totally on you. I don't see how this could or should be added to this library as it sounds very specific to you.

Makes sense. Sounds like this is something that can be done using Custom icons. 

Thanks for clearing up feel free to close.

**Comment by clayms** [comment]
Oh... If all you wanted was Nodes with your own icons , then yes, `Custom` Nodes, is what you want.  

See the [Diagrams Custom example](https://diagrams.mingrammer.com/docs/getting-started/examples#rabbitmq-consumers-with-custom-nodes).
Also, see this issue https://github.com/mingrammer/diagrams/issues/196#issuecomment-722512945 .


You can also use the `Node` class directly and specify the `image` parameter to point to the path to the icon you want to use.
See these issue comments, among many others.
https://github.com/mingrammer/diagrams/issues/410#issuecomment-746631341
https://github.com/mingrammer/diagrams/issues/450#issuecomment-769829352

**Comment by kenichi-shibata** [comment]
Thanks got it 👍
