### ISSUE TITLE
Creating subgraphs with rank attribute?

### ISSUE THREAD

**Issue by anidue** [mingrammer/diagrams#486]
I am really sorry for this question. But I checked yesterday night and today for several hours and sadly could not find anything about creating subgraphs using this great package.

I know in the dot language it would be something like this:
```code
    subgraph co2graph {
        rank=same
        co2node1[style="filled", label="CO2"]
        co2node2[style="filled", label="CO2"]
        co2node3[style="filled", label="CO2"]
    }
```
or for subgraphs inside clusters something like this:
```code
subgraph cluster {
        // creates subgraph inside cluster (only subgraph can have rank)
        subgraph co2graphInsideCluster{
        rank=same
        co2node4[style="filled", label="CO2"]
        }
    }
```

Could someone please tell me how to create subgraphs using this package? I only understood how to create clusters. But now I need to create ranked subgraphs inside clusters.

My cluster code currently:
```code
with Cluster(""):
        # TODO: how to create subgraph here with ranked attribute?
        co2node = Node("CO2")
```

any help is greatly appreciated!

greetings

**Comment by clayms** [comment]
All three "roles" described in the "Subgraphs and Clusters" section of [The DOT Language documentation](https://www.graphviz.org/doc/info/lang.html) should work using this library.

I have never been able to [rank](https://www.graphviz.org/doc/info/attrs.html#d:rank) to work on `Cluster`s in this library.  However, the `Edge` parameters [`constraint`](https://www.graphviz.org/doc/info/attrs.html#d:constraint) and [`minlen`](https://www.graphviz.org/doc/info/attrs.html#d:minlen) have done the trick.

Note: these only work for the dot layout engine, which is the default for this library.

Example: 

```python
from diagrams import Diagram, Cluster, Edge, Node

graph_attr = {
    "spline":"splines",
    "label":"Clusters with Diagrams"
}

co1graph_attr = {
    "label":"rank=same with 'constraint' Edge parameter",
}

co2graph_attr = {
    "label":"rank=same with 'minlen' Edge parameter",
}

dir2graph_attr = {
    "label":"cluster with ranking",
}

with Diagram("edge labels", show=False, graph_attr=graph_attr) as diag:

    with Cluster("co1graph", graph_attr=co1graph_attr):
            co1node1 = Node(style="filled", label="CO1-1")
            co1node2 = Node(style="filled", label="CO1-2")
            co1node3 = Node(style="filled", label="CO1-3")

            (
                co1node1 >> Edge(constraint="False") >>
                co1node2 >> Edge(constraint="False") >> 
                co1node3
            )

    with Cluster("co2graph", graph_attr=co2graph_attr):
            co2node1 = Node(style="filled", label="CO2-1")
            co2node2 = Node(style="filled", label="CO2-2")
            co2node3 = Node(style="filled", label="CO2-3")

            (
                co2node1 >> Edge(minlen="0") >>
                co2node2 >> Edge(minlen="0") >> 
                co2node3
            )

    co1node1 - Edge(penwidth="0.0") - co2node3

    with Cluster("dir2graph", graph_attr=dir2graph_attr):
            dir2node1 = Node(style="filled", label="Dir2")
            dir2node2 = Node(style="filled", label="Dir2")
            dir2node3 = Node(style="filled", label="Dir2")

            (
                dir2node1 >>
                dir2node2 >> 
                dir2node3
            )

diag
```


![image](https://user-images.githubusercontent.com/12793783/111172517-45e4e600-857c-11eb-8751-27e8efa03dd3.png)

**Comment by anidue** [comment]
Hey clayms,

thank you so much for your help! This was a nice trick. You saved me.
