### ISSUE TITLE
Add TODOs Badge to README

### ISSUE THREAD

**Issue by patrickdevivo** [mingrammer/diagrams#49]
Hi there! I wanted to propose adding the following badge to the README to indicate how many `TODO` comments are in this codebase:

[![TODOs](https://badgen.net/https/api.tickgit.com/badgen/github.com/mingrammer/diagrams)](https://www.tickgit.com/browse?repo=github.com/mingrammer/diagrams)

The badge links to `tickgit.com` which is a free service that indexes and displays TODO comments in public github repos. It can help surface latent work and be a way for contributors to find areas of code to improve, that might not be otherwise documented.

The markdown is:

```
[![TODOs](https://badgen.net/https/api.tickgit.com/badgen/github.com/mingrammer/diagrams)](https://www.tickgit.com/browse?repo=github.com/mingrammer/diagrams)
```

Thanks for considering, feel free to close this issue if it's not appropriate or you prefer not to!

(full disclosure, I am the creator/maintainer of `tickgit`)

**Comment by mingrammer** [comment]
Looks good. You can add that badge to README.md. Send me a PR with these requirements, please.

- I prefer the lowercases for badge titles, so use `todos` for the title.
- Place the `todos` badge in front of the first `provider` badge. (because of provider badge can continue to add)
