### ISSUE TITLE
Connect 2 list based on some relation

### ISSUE THREAD

**Issue by jimitshah77** [mingrammer/diagrams#493]
> I know you can't connect two lists directly because shift/arithmetic operations between lists are not allowed in Python.

But I was thinking of a feature where you can connect 2 list based on some relation.

- one-to-many
- many-to-many 
- one-to-one

Basically based on the relation we can decompose the request to a list and element instead of performing operation between 2 lists

For Example: 
```
list_a = [A,B,C]
list_b = [D,E,F]
```
1 >> n
```
A >> [D,E,F]
B >> [D,E,F]
C >> [D,E,F]
```
n - n
```
A - [D,E,F]
B - [D,E,F]
C - [D,E,F]

OR
  
[A,B,C] - D
[A,B,C] - E
[A,B,C] - F
```
1 - 1
```
A - D
B - E
C - F
```
I would like to know your thoughts and suggestion! 

> (Also I am new here, let me if there are some beginners issues which can help me get started. Thank you!)

**Comment by clayms** [comment]
@jimitshah77 

Your "1 >> n" and "n - n" cases are identical, only the `Edge`s don't have arrowheads.
Your "1 - 1" case would only work if the length of each list is identical.

For the first case, you can write your own `nodelist_to_nodelist` function.
For the second case, simply change the  `nd >> l2` to ` nd - l2` in the `nodelist_to_nodelist` function.

```python

from diagrams import Diagram, Node

def nodelist_to_nodelist(l1:list, l2:list) -> None:
    for nd in l1:
        nd >> l2


with Diagram("", show=False, direction="TB") as diag:
    nd_names = ["A","B","C","D","E","F"]
    for name in nd_names:
        exec(f'{name} = Node("{name}", labelloc="c")')

    list_a = [A,B,C]
    list_b = [D,E,F]

    nodelist_to_nodelist(list_a, list_b)

diag
```

![image](https://user-images.githubusercontent.com/12793783/112374354-60c00480-8cb8-11eb-836a-4b6fac932ba9.png)


For the third case, you can write a function that will only connect nodes in order up to the length of the smallest list.  I made `list_b` longer to make the point.   
Again, if you don't want the `Edge` arrowheads, just change it from `>>` to `-` in the function.

```python
def ordered_pairing(l1:list, l2:list) -> None:
    min_len = min(len(l1), len(l2))
    for i in range(min_len):
        l1[i] >> l2[i]


with Diagram("", show=False, direction="TB") as diag:
    nd_names = ["A","B","C","D","E","F","G","H"]
    for name in nd_names:
        exec(f'{name} = Node("{name}", labelloc="c")')

    list_a = [A,B,C]
    list_b = [D,E,F,G,H]

    ordered_pairing(list_a, list_b)

diag
```

![image](https://user-images.githubusercontent.com/12793783/112377045-a0d4b680-8cbb-11eb-9437-01549b128dd6.png)

**Comment by jimitshah77** [comment]
Thanks @clayms for the detailed explanation, this solves the problem. 
Maybe we can include a check, if both the nodes are list then call this nodelist_to_nodelist() function, instead of throwing the error "You can't connect two lists directly because shift/arithmetic operations between lists are not allowed in Python." 
Yeah, but first I will have to check how the code works internally.

**Comment by clayms** [comment]
have a look at 

https://github.com/mingrammer/diagrams/blob/ac4e502277dcf0850214ca34103c39a805904dd6/diagrams/__init__.py#L376
and
https://github.com/mingrammer/diagrams/blob/ac4e502277dcf0850214ca34103c39a805904dd6/diagrams/__init__.py#L386

**Comment by jimitshah77** [comment]
Thank you @clayms for directing me towards that point in the code... Much appreciated!
I'll close the issue now and start working on it.

**Comment by fawaf** [comment]
has this been done yet? since this issue is closed.
