### ISSUE TITLE
Please add a license to this repo

### ISSUE THREAD

**Issue by mbrukman** [mingrammer/diagrams#5]
Thank you for writing this and making it available to the public!

Just wanted to note that the [`README.md`][readme] says:

> ## License
>
> [MIT](LICENSE.md)

Unfortunately, `LICENSE.md` does not exist in the repo. You can get a copy of the [MIT license at the OSI][osi-mit] to add to the repo. Thanks again!

[readme]: https://github.com/mingrammer/diagrams/blob/ae175ffd3254d89ad99724836fd7d68a6875df15/README.md#license
[osi-mit]: https://opensource.org/licenses/MIT

**Comment by mingrammer** [comment]
I added it! Thanks for reporting!
