### ISSUE TITLE
Direction is broken when a cycle is introduced

### ISSUE THREAD

**Issue by drorata** [mingrammer/diagrams#501]
Consider the following example:

```python
from diagrams import Diagram
from diagrams.gcp.analytics import BigQuery

with Diagram("Detailed View", show=False, curvestyle="curved"):
    foo = BigQuery("foo")
    bar = BigQuery("bar")
    goo = BigQuery("goo")

    foo >> bar >> goo >> foo
```

which yields the following:

![image](https://user-images.githubusercontent.com/2905978/112994982-0f59be80-916b-11eb-95a6-5710fc21bd23.png)
 
Note the wrong direction of the edge going from `goo` back to `foo`. Am I missing something?

**Comment by clayms** [comment]
Setting `curvestyle` to `"curved"` is an issue, even in the underlying graphviz library. 

Quickest fix is to just delete `curvestyle="curved"`.

![image](https://user-images.githubusercontent.com/12793783/113036945-d9184100-9162-11eb-976a-58c034293bc8.png)


A better fix is to set the `graph_attr` dictionary key `"splines"` to the value: `"spline"`, `"polyline"`, or `"line"`.

`"spline"` output below:

```python
from diagrams import Diagram
from diagrams.gcp.analytics import BigQuery

graph_attr = {
    "splines":"spline",
}

with Diagram("Detailed View", show=False, graph_attr=graph_attr):
    foo = BigQuery("foo")
    bar = BigQuery("bar")
    goo = BigQuery("goo")

    foo >> bar >> goo >> foo
```

![image](https://user-images.githubusercontent.com/12793783/113036316-1fb96b80-9162-11eb-9b06-214acd552605.png)

**Comment by drorata** [comment]
Thanks a lot that worked much better!
