### ISSUE TITLE
Node Label Positioning

### ISSUE THREAD

**Issue by cldeluna** [mingrammer/diagrams#503]
Hi,

I'm having trouble properly positioning the Node label.
I started out using the Custom node type but then found I had better control using Node but I still can't manipulate the node label positioning.  I am using a custom image icon so i'm thinking I have to define its boundaries for some of the label controls to work properly?  

I've tried every label positioning option that I though might make sense and most dont' have any impact.

I'm hoping someone can point me in the right direction or point out the error of my ways!

Thank you in advance!

Claudia

```
for link in ws_list:

            #lp="72"   labelloc="c", labeljust="r", imagepos="br" <-- no change

            # imagepos https://www.graphviz.org/doc/info/attrs.html#d:imagepos

            end_node = Node(image=ilib["rtrbc"], label=f"\n{link['DESTINATION_HOST']}\n{link['PLATFORM']}\n{link['MANAGEMENT_IP']}", fontcolor="blue",fontsize="18",  labeldistance="25", width="1", height="1")

            origin >> Edge(label=f"{link['LOCAL_PORT']}--> {link['REMOTE_PORT']}", minlen="5", color="blue", fontsize="38", penwidth="5") >> end_node
```

![node-label-2021-03-30_10-34-59](https://user-images.githubusercontent.com/6796247/113033118-82e8d500-9145-11eb-933f-80356d017fb4.png)

**Comment by clayms** [comment]
You'll have to add space in such a way to "push" the label up from the bottom `"b"` or down from the top `"t"`.

```python
from diagrams import Diagram, Node

with Diagram("{}label location".format("\n"*6), show=False):
    (
        Node("Add space\nto push up\nfrom bottom{}".format("\n"*8), labelloc="b")
        -
        Node("{}Add space\nto push down\nfrom top".format("\n"*7), labelloc="t")
    )
```
![image](https://user-images.githubusercontent.com/12793783/113174753-afb9ec80-9218-11eb-921d-37e9a601040e.png)

**Comment by cldeluna** [comment]
@clayms  I actually started with the line feed approach but it did not seem to make any difference.
At this point I think you've shared all the "tools" in the toolbelt of label manipulation that are relevant and I have to assume its something relating to the icons I'm using.  I need to play around with them.

end_node = Node(image=ilib["rtrbc"], label=f"\n\n\n\n\n\n{link['DESTINATION_HOST']}\n{link['PLATFORM']}\n{link['MANAGEMENT_IP']}", labelloc="b", fontcolor="blue",fontsize="18")

Tried with the f-string and with the .format as you showed.

You can close this out or keep it open so I can report back anything I find.
I'll get out of your hair (on this topic at any rate).

Thanks!!

![label-2021-03-31_13-53-34](https://user-images.githubusercontent.com/6796247/113210023-9faa0900-9228-11eb-88d1-4b041553e079.png)

**Comment by clayms** [comment]
@cldeluna, no problem.

I am curious to see why it is not working.  Might be a version issue.  My version and sys info are below the diagram below.

I don't have the same icon as you, but below is what I did and the output seems to be what you are after.  

```python

from diagrams import Diagram, Node

link = {
    'DESTINATION_HOST':'HQ-R360',
    'PLATFORM': 'cisco-WS-C269OS-48RFPD-L',
    'MANAGEMENT_IP': '101.202.303.404',
}

with Diagram("{}label location".format("\n"*2), show=False):
    end_node = Node(
        label="{}\n{}\n{}{}".format(
            link['DESTINATION_HOST'], link['PLATFORM'], link['MANAGEMENT_IP'], "\n"*6), 
        labelloc="b", fontcolor="blue", fontsize="18",
        image="img/cisco-wireless-router.png")
```

![image](https://user-images.githubusercontent.com/12793783/113229090-3d6ef980-9264-11eb-8be8-be6adb6a3c71.png)





```bash
$ dot -v
dot - graphviz version 2.38.0 (20140413.2041)
libdir = "/usr/lib64/graphviz"
Activated plugin library: libgvplugin_dot_layout.so.6
Using layout: dot:dot_layout
Activated plugin library: libgvplugin_core.so.6
Using render: dot:core
Using device: dot:dot:core
The plugin configuration file:
        /usr/lib64/graphviz/config6
                was successfully loaded.
    render      :  cairo dot fig map pic pov ps svg tk vml xdot
    layout      :  circo dot fdp neato nop nop1 nop2 osage patchwork sfdp twopi
    textlayout  :  textlayout
    device      :  canon cmap cmapx cmapx_np dot eps fig gv imap imap_np ismap pdf pic plain plain-ext png pov ps ps2 svg svgz tk vml vmlz xdot xdot1.2 xdot1.4
    loadimage   :  (lib) eps gif jpe jpeg jpg png ps svg
```

```bash
$ pip freeze
...
diagrams==0.18.0
...
graphviz==0.13.2
...
```

```bash
$ cat /etc/*-release
LSB_VERSION=base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
NAME="Amazon Linux AMI"
VERSION="2018.03"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2018.03"
PRETTY_NAME="Amazon Linux AMI 2018.03"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2018.03:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"
Amazon Linux AMI release 2018.03
```

**Comment by cldeluna** [comment]
@clayms   Spot on as usual!  My goof was that I was putting the new line at the start of the label string!  Its also interesting that if I put too many new lines it seems to loop back on itself.

This seems to be the sweet spot:

end_node = Node(image=ilib["rtrbc"], label=f"{link['DESTINATION_HOST']}\n{link['PLATFORM']}\n{link['MANAGEMENT_IP']}**\n\n\n\n\n**", labelloc="b", fontcolor="blue",fontsize="18")


![label_working_2021-04-02_10-03-47](https://user-images.githubusercontent.com/6796247/113437323-46aeb200-939b-11eb-85a6-f71bf6167479.png)

And if I manipulate the label string a bit more (2 lines vs 3) its perfect!

Thank you!!

![labels-2-lines-2021-04-02_10-13-35](https://user-images.githubusercontent.com/6796247/113445169-38b45d80-93aa-11eb-96de-ca96d117428e.png)

**Comment by cldeluna** [comment]
Thank you for the great support!

**Comment by sez76** [comment]
> See if this helps:
> 
> also see https://www.graphviz.org/doc/info/attrs.html#k:escString
> 
> ```python
> from diagrams import Diagram, Node
> 
> with Diagram("\nlabel location", show=False):
>     bot_rgt = Node("Bottom\\rRight\\r", labelloc="b")
>     bot_cen = Node("Bottom\nCenter", labelloc="b")
>     bot_lft = Node("Bottom\lLeft\l", labelloc="b")
> 
>     cen_rgt = Node("Center\\rRight\\r", labelloc="c")
>     cen_cen = Node("Center\nCenter", labelloc="c")
>     cen_lft = Node("Center\lLeft\l", labelloc="c")
> 
>     top_rgt = Node("Top\\rRight\\r", labelloc="t")
>     top_lft = Node("Top\lLeft\l", labelloc="t")
>     top_cen = Node("Top\nCenter", labelloc="t")
> 
>     bot_lft - bot_cen - bot_rgt
>     cen_lft - cen_cen - cen_rgt
>     top_lft - top_cen - top_rgt
> ```
> 
> ![image](https://user-images.githubusercontent.com/12793783/113042720-855d2600-9169-11eb-9af4-fd39af697d1e.png)

Hi, do you know if is possible to use your example, but with nodes directly to have image on the node bottom right
```pyhton
with Diagram("\nlabel location", show=False):
    bot_rgt = Node("Bottom\\rRight\\r", labelloc="b")
```
