### ISSUE TITLE
Nesting Nodes

### ISSUE THREAD

**Issue by cldeluna** [mingrammer/diagrams#505]
Hi,

Im working on documenting a cable plant with Diagrams.  I essentially have a JSON file (shown as CSV below).

As you can see most of the cabling stars out from Rack1.  

Src,to,Dst,strands,type,Notes,grouping
Rack1,to,Rack2,24,OM3/OM4,,
Rack1,to,Rack3,24,OM3/OM4,,
Rack1,to,Rack4,24,OM3/OM4,,
Rack4 ,to,Rack10,25,OM3/OM5,,
Rack10,to,Rack11,26,OM3/OM6,,

My thought was to loop through my JSON data to draw out the fiber connections thinking that since nodes had the same name the right "nesting" would take place:

`
with Diagram("\n\n\nSample Nested Fiber Links", show=False):

    for link in data:

        image = "icons/icons8-coil-50_aqua.png"

        src = Node(
            label=f"{link['Src']}", 
            labelloc="t", fontcolor="black", fontsize="18",
            image=image
        )

        dst = Node(
            label=f"{link['Dst']}", 
            labelloc="b", fontcolor="black", fontsize="18",
            image=image
        )
 
        src >> Edge(label=f"{link['type']}\n{link['strands']}", minlen="1") >> dst   `

However rather than links "starring" out of Rack1 and then nested links behind Rack4, here is the result.

![sample_nested_fiber_links](https://user-images.githubusercontent.com/6796247/113485571-14688780-9463-11eb-84ee-45565ee7d3ef.png)

Here is what I was expecting (built out manually)

![sample_nested_fiber_links_manual](https://user-images.githubusercontent.com/6796247/113485465-7379cc80-9462-11eb-8f9e-d79e541e51f8.png)

I'm sure Im just not thinking about things correctly so I'm hoping someone can set me straight.

Thank you!

**Comment by clayms** [comment]
You're creating new nodes for every line in your json file. So you are creating the `rack1` Node three separate times.

You'll have to extract a list of unique Nodes first, loop over that list to make the nodes, then loop over your json to connect the nodes.

**Comment by cldeluna** [comment]
Thanks @clayms, Yes..I figured that out late last night!  I also didn't realize that you have to make the cluster nodes within the cluster context.  (I knew my lack of familiarity with context managers was likely why I was having such a hard time!). Thanks for the gentle nudge in the right direction!  
Have I mentioned how much I love this module?
