### ISSUE TITLE
Node previews in Documentation

### ISSUE THREAD

**Issue by m1racoli** [mingrammer/diagrams#509]
Currently the documentation on nodes only lists all available node classes. Considering those nodes are meant to visually represent something, it would be great if the documentation would render a preview of each node class. This would make it much easier to find the right node class by its visual representation in certain cases.

**Comment by clayms** [comment]
Also see

https://github.com/mingrammer/diagrams/issues/466

https://github.com/mingrammer/diagrams/pull/499

https://github.com/mingrammer/diagrams/issues/78

**Comment by mingrammer** [comment]
The website is updated by #499.
