### ISSUE TITLE
Client node support

### ISSUE THREAD

**Issue by nerixim** [mingrammer/diagrams#53]
Thanks for your work.

Could you consider to add nodes for clients, like a smartphone or PC? I'm not sure if that's in the scope of the project but it would be great if you could show connections between front-end (CloudFront etc) nodes and client.

**Comment by mingrammer** [comment]
#55 can resolve it.

**Comment by mingrammer** [comment]
Oh, there are no PCs or Smartphone types. I'll support those them.

**Comment by mingrammer** [comment]
Diagrams v0.6.5 is now released with client support.
