### ISSUE TITLE
Newest install not reflecting update Azure icons

### ISSUE THREAD

**Issue by jtandrew** [mingrammer/diagrams#533]
It appears in #494 multiple icons were added and/or updated but it is not reflecting in version 0.19.1

Is this a bug? Or would I need to do a source build locally to see the updates?

Thanks!
Jim

**Comment by gabriel-tessier** [comment]
The PR was merged with master but the 0.19 version is older and don't have this change, you may need the 0.20 version which may release soon! 

@mingrammer 
Maybe better to make a roadmap there's a lot of PR waiting and several version can be released, need to update the documentation and add more unit test...
If you want I can help.

**Comment by jtandrew** [comment]
Fixed in 0.20
