### ISSUE TITLE
The problem of image resolution

### ISSUE THREAD

**Issue by Fcscanf** [mingrammer/diagrams#535]
In the process of drawing large-scale architecture diagram, the rendering is fuzzy because of more nodes, how to solve the problem of unclear
![image](https://user-images.githubusercontent.com/27654200/119244530-34cfdb00-bba4-11eb-8e9d-7c0da9eda00e.png)

**Comment by clayms** [comment]
Try setting the `resolution` graph attribute.

https://graphviz.gitlab.io/doc/info/attrs.html#d:resolution

You'll have to put that attribute and the resolution you want as a floating point number in a `graph_attr` dictionary similar to the one in the following example.

https://github.com/mingrammer/diagrams/issues/475#issuecomment-786812352

**Comment by Fcscanf** [comment]
OK，thanks
