### ISSUE TITLE
Is there a way to add a ring around connectors?

### ISSUE THREAD

**Issue by jcrsantiago** [mingrammer/diagrams#544]
I need a way to add a ring around the connectors. Here is an example. Ideally, I can also put a note in or around the circle.

![image](https://user-images.githubusercontent.com/49008662/122133889-6da14f80-cdf2-11eb-81ed-7c7fad8d7302.png)

**Comment by clayms** [comment]
For simple cases, you can use `headclip` and tailclip` to make the Edges *appear* to go through a "ring" node in the middle.  For more complex cases like your example, you will have to use the neato layout engine and specify the position of each Node.


simple case: 
```python 

from diagrams import Diagram, Node, Edge

graph_attr = {
    "splines":"ortho",
}


with Diagram("\n\nedge rings", graph_attr=graph_attr, show=False) as diag:
    n1 = Node("n1")
    n2 = Node("n2")
    en1 = Node("VPC\n\n\n\n55", labelloc="c", shape="oval", height="2", width=".5")
    
    n1 - Edge(label="E1/7", minlen="2", headclip="False") - en1- Edge(label="E1/7", minlen="2", tailclip="False") - n2
    n1 - Edge(label="E1/8", minlen="2", headclip="False") - en1- Edge(label="E1/8", minlen="2", tailclip="False") - n2
```

![image](https://user-images.githubusercontent.com/12793783/122778967-74f5ac80-d27b-11eb-9888-b43ac7c142e3.png)


To make you more complex example, see the following examples using the neato layout engine.

https://github.com/mingrammer/diagrams/issues/290#issuecomment-719983090

https://github.com/mingrammer/diagrams/issues/243#issuecomment-721971788

https://github.com/mingrammer/diagrams/issues/111#issuecomment-722027483

**Comment by jcrsantiago** [comment]
Oh wow I had googled everywhere and couldn't find this. I hope that they add more examples in the docs, it would be very helpful.
