### ISSUE TITLE
Debian support for generic.os class ?

### ISSUE THREAD

**Issue by seboss666** [mingrammer/diagrams#549]
Hello,

I'm pretty surprised not to find Debian in the supported generic.os section : https://diagrams.mingrammer.com/docs/nodes/generic#genericos

Thought it was a mistake so I went to the os.py version, and managed to add it myself (yes, before reading the contributing guide, so it was a little rough :D)

As I found no existing/closed PR or any existing/closed issue regarding this, is there something already planned to add it, or is there something blocking (like licenses on logos, yes even with Debian) ?

**Comment by gabriel-tessier** [comment]
@seboss666 
You can always create a PR, for licenses on logo I think you can easily find one Creative Common icon.

`managed to add it myself ` <--- just for information you can use custom and add any icon for yourself. https://diagrams.mingrammer.com/docs/nodes/custom

But for Debian I think a PR will be more useful!

**Comment by bdsoha** [comment]
@mingrammer @seboss666 This has been added in #570 and can be closed.

**Comment by seboss666** [comment]
Thanks for noticing :)
