### ISSUE TITLE
Are there any example libraries for diagrams

### ISSUE THREAD

**Issue by jcrsantiago** [mingrammer/diagrams#553]
I often want to learn what are the best ways to do something I might want to do. The easiest way is to find examples that are similar to what I am looking for as a starting point. Here and on the homepage there are a couple of examples of how to do things, but is there a place with lots of examples of what people have done as a way to learn what can be done?

**Comment by gabriel-tessier** [comment]
@jcrsantiago 

According to the readme:
> Let me know if you are using diagrams! I'll add you in showcase page. (I'm working on it!) :)

So something is planned but not yet done. If the examples of the website are not enough you can check in the issues there's a couple of examples that can help also there's blog here and there.

If you have an idea about what you want to do but don't know how to, you can always try something then open an issue and we can certainly help you build your beautiful diagrams.
