### ISSUE TITLE
Search Option for the service

### ISSUE THREAD

**Issue by satyabansahoo2000** [mingrammer/diagrams#557]
Hi. Can we get a search option to search for the icon? It will be easy to look up for the icons and directly import without searching everywhere where it could have existed. 
Like showing the results of all loadbalancers at one place. Then import whichever we need.

**Comment by gabriel-tessier** [comment]
@satyabansahoo2000 

I think it can be related to this PR:
https://github.com/mingrammer/diagrams/pull/499

But usually you know which provider you use and I think finding the resources is straightforward. In first place you know your provider and you also know that the loadbalancer is inside network... 
As I  understand your need, you want to use whatever loadbalancer in any architecture, I think it's not  the correct way to go as you will lost coherence. For example if you use an Azure loadbalancer icon in a AWS architecture diagrams and melt providers somebody reading your diagrams will not understand it. But after all you are free to use it like you want.

If you can provide more information for your need it can help to provide a better answer and maybe a new feature.

**Comment by satyabansahoo2000** [comment]
Thanks for the PR you have provided, but that's not the issue.

So, let's say I want AWS compute or some other, I have to search whole AWS page to see where it is. I just want a search option so that the particular comes up at the top and easily copy the code. 

Also, there's the option on the right side of the page we can redirect to particular service like compute, security or other, but again scrolling and searching. 

If any possibility of this feature, then it will be a great help I believe.

**Comment by gabriel-tessier** [comment]
@satyabansahoo2000 

Ok I got it about the search but I mess one parts of your comment, 

> Then import whichever we need.

Maybe this issue https://github.com/diagrams-web/diagrams-web/issues/6 will more match. 
/!\ diagrams-web is a different project but just about the concept.
I need to check how it can be done so you only have to copy paste the import. It can be a good improvement.

**Comment by satyabansahoo2000** [comment]
@gabriel-tessier Yes, exactly like that. Thanks and looking forward to see it improve.
