### ISSUE TITLE
Text overlaps in a lot of diagrams 

### ISSUE THREAD

**Issue by drogerschariot** [mingrammer/diagrams#585]
We tend to have long label names for our Nodes, and the text overlaps each other in a lot of diagrams like so:

![Screenshot at 2021-08-18 12-39-26](https://user-images.githubusercontent.com/1655964/129938171-082f6907-380e-4b22-8bd3-e9f889167a78.png)

Is it possible to customize the labels that if they overlap, increase the arrow length?

**Comment by clayms** [comment]
either break the name up with `\n` in the node's label, or use `minlen` `Edge` parameter to increase the space between successive ranked nodes.

see: 
https://github.com/mingrammer/diagrams/issues/352#issuecomment-721985338
https://github.com/mingrammer/diagrams/issues/185#issuecomment-722381623
https://github.com/mingrammer/diagrams/issues/364#issuecomment-719957643

**Comment by drogerschariot** [comment]
Edge did the trick with `minlen`, thanks @clayms !!
