### ISSUE TITLE
Add Firebase icon

### ISSUE THREAD

**Issue by pshevtsov** [mingrammer/diagrams#59]
I'd like to submit a pull request with adding the icon for [Firebase](https://firebase.google.com).

![firebase](https://user-images.githubusercontent.com/290451/76235994-04b94800-623d-11ea-9b5b-f7a1626ecb06.png)

I'm just not sure in which section, since it's not actually a Google Cloud Platform product.

Any suggestions, @mingrammer?

**Comment by mingrammer** [comment]
Hm .. since it is a standalone cloud service, how about just new category, the `firebase` provider?

Any better ideas? :)

**Comment by Shimpei-GANGAN** [comment]
I'd like too to submit a pull request with adding the icon for  Firebase and Firebase Hosting icon, etc. .

Firebase is one of the BaaS services.
So, I would like to propose a new provider, baas. Then you can categorize them as follows:

- diagrams.baas.firebase.icon
- diagrams.baas.firebase.hosting
- diagrams.baas.firebase.authentication

We think it will be easy to respond when we want to add Baas services in the future.

What do you think? @mingrammer

**Comment by mingrammer** [comment]
@Shimpei-GANGAN Sounds good to me. `baas` provider is more general for that.

But what is `diagrams.baas.firebase.icon`? `firebase.icon` means icon image of firebase? or is there service called `icon` (I have no experience with firebase)

Thank you.

**Comment by Shimpei-GANGAN** [comment]
That's right. Firebase.icon is the icon image of Firebase.

> But what is diagrams.baas.firebase.icon? firebase.icon means icon image of firebase? or is there a service called icon?

I think it's very good.
> If you mean the icon image, diagrams.baas.firebase.firebase would be better I think.


I'd like to issue two separate pull requests for the addition of new providers.
