### ISSUE TITLE
No text rendered under alpine linux

### ISSUE THREAD

**Issue by quiteDEADlee** [mingrammer/diagrams#610]
I've created an alpine linux docker container with graphviz, python3 and pip installed and everything is working fine except that instead of text I get unicode boxes:
![web_service](https://user-images.githubusercontent.com/20325986/139166576-dc03b014-1a4c-4a08-a2e2-926e08530003.png)
Is this just missing fonts or something? Were does diagrams get it's text from?

thank you!

**Comment by Karreg** [comment]
Thanks ! I just had this issue in my devcontainer...
@mingrammer maybe it would be good to have this dependency documented alongside graphviz dependency?
