### ISSUE TITLE
Specify dot executable path?

### ISSUE THREAD

**Issue by faxg** [mingrammer/diagrams#62]
I want to run in an environment (Azure Functions) where I have limited control over the setup other than listing dependencies in requirements.txt. This makes the code fail e.g. because the „dot“ executable is not in the PATH. Is there a way to specify the full path or otherwise get this running?

**Comment by mingrammer** [comment]
Not yet. Hm .. I think this issue is out of scope of this package.

**Comment by spidgorny** [comment]
See [here](https://github.com/xflr6/graphviz/issues/123) for a workaround
