### ISSUE TITLE
Spurious padding around nodes

### ISSUE THREAD

**Issue by fdv1** [mingrammer/diagrams#639]
Hi, thanks for this awesome tool! I can't reproduce exactely the examples from the tutorial as it seems that the nodes have some kind of implicit padding which prevents arrows from connecting to them properly. 
![grouped_workers](https://user-images.githubusercontent.com/22858925/149119926-2a331f6d-866a-4918-ab64-a3aca5404419.png)
I am using diagrams 0.20.0 with graphviz 2.50 on macOS.
Best,
Francois

**Comment by singha200** [comment]
Hi @fdv1,

Cna you please provide the link for the example you are trying ?

**Comment by fdv1** [comment]
Sorry I should have been more specific. I used the code below which is the first example featured in the examples section.

from diagrams import Diagram
from diagrams.aws.compute import EC2
from diagrams.aws.database import RDS
from diagrams.aws.network import ELB

with Diagram("Grouped Workers", show=False, direction="TB"):
    ELB("lb") >> [EC2("worker1"),
                  EC2("worker2"),
                  EC2("worker3"),
                  EC2("worker4"),
                  EC2("worker5")] >> RDS("events")

**Comment by clayms** [comment]
@fdv1 
This library increases the height of the `Node`s so the label displays under the `Node` image.  The default `imagepos` attribute is `"c"` (center).  Together, these two conspire to give the extra padding at the top of the `Node`.  

You will have to specify the `imagepos` to be `"tc"` (top center), and slightly decrease the `Node` height to make the `Edge` appear to truncate at the `Node`s image boundary. 

```python

with Diagram("Grouped Workers", show=False, direction="TB"):
    ELB("lb") >> [
        EC2("worker1", height="1.6", imagepos="tc"),
        EC2("worker2", height="1.6", imagepos="tc"),
        EC2("worker3", height="1.6", imagepos="tc"),
        EC2("worker4", height="1.6", imagepos="tc"),
        EC2("worker5", height="1.6", imagepos="tc"),
    ] >> RDS("events", height="1.6", imagepos="tc")
```


![image](https://user-images.githubusercontent.com/12793783/150688482-de604f29-92e1-4aad-aa98-d6aeba54fe45.png)

**Comment by fdv1** [comment]
That's much neater, thanks for your help!
