### ISSUE TITLE
Custom Edge adds Arrows

### ISSUE THREAD

**Issue by askpatrickw** [mingrammer/diagrams#643]
When expressing relations between nodes with custom edges you get arrows you don't get without custom edges.

```python
from diagrams import Cluster, Diagram, Edge
from diagrams.azure.compute import AppServices


graph_attr = {"bgcolor": "white", "labelloc": "t", "fontsize": "30"}

with Diagram("Bugs in Edges", show=False, graph_attr=graph_attr):
    custom_edge = Edge()
    with Cluster("Why Arrows with custom Edge?"):
        service_4 = AppServices("4")
        service_5 = AppServices("5")
        service_6 = AppServices("6")

        service_4 - service_5 - service_6

        service_d = AppServices("d")
        service_e = AppServices("e")
        service_f = AppServices("f")

        service_d - custom_edge - service_e - custom_edge - service_f
```

![image](https://user-images.githubusercontent.com/4002194/149677385-a7315291-f9cd-4ab4-93af-8675ccf0ef4b.png)

**Comment by clayms** [comment]
How are you defining `custom_edge` ?   It must be defined somewhere, or this code would not even run.

**Comment by askpatrickw** [comment]
Sorry.. cut and paste error. I added that line back in.

**Comment by clayms** [comment]
Running your exact code I don't get the arrow heads.

```shell
$ dot -v

dot - graphviz version 2.50.0
```
```shell
$ pip freeze | grep diagrams

diagrams==0.20.0
```
```shell
$ hostnamectl | grep Kernel


Kernel: Linux 5.16.0-arch1-1
```





![image](https://user-images.githubusercontent.com/12793783/150686085-284bbeda-347b-4f8d-8719-2d89bf93d91a.png)

**Comment by askpatrickw** [comment]
we decided not to use this so I won't be following up. closing.

**Comment by fritx** [comment]
@askpatrickw what was your alternative?
