### ISSUE TITLE
Single point for node connections

### ISSUE THREAD

**Issue by samcro1967** [mingrammer/diagrams#647]
Is there a way to get all connections to a node to connect at a single point?  I have tried specifying tailport=s, but they all go to a different point on the bottom of the node.  Is there another option to accomplish this?

Here is what I have right now:
![image](https://user-images.githubusercontent.com/2319445/152703125-83080907-f473-4570-8a9f-7cf87cd82382.png)

Here is what I would like to have:
![image](https://user-images.githubusercontent.com/2319445/152703092-be400bc2-3acf-40eb-9c27-09caefe2b0a7.png)

**Comment by clayms** [comment]
Please post your code.

Have a look at the following issue comments:

https://github.com/mingrammer/diagrams/issues/358#issuecomment-723652479
https://github.com/mingrammer/diagrams/issues/593#issuecomment-914719240
