### ISSUE TITLE
Adding Celery

### ISSUE THREAD

**Issue by gabriel-tessier** [mingrammer/diagrams#68]
Hi,

I needed celery (http://www.celeryproject.org/) icon for a diagrams and I add it in my fork: https://github.com/gabriel-tessier/diagrams

I wonder If I can make a PR for this as nobody so far asked for celery.
Is there rule about adding a new resource or we can add any ressource and push a PR?

Maybe some lines in the contribution guide can help. 

Thanks again for this great software!

**Comment by thedrow** [comment]
Celery maintainer here. I'd really like this issue to be resolved.
What can I do to help?

**Comment by djalexd** [comment]
Hi,

I've extended the library locally by including some classes and icons.

It's as easy as providing them similarly to other classes. For example:
https://github.com/mingrammer/diagrams/blob/master/diagrams/k8s/__init__.py
https://github.com/mingrammer/diagrams/tree/master/resources/k8s/compute

**Comment by gabriel-tessier** [comment]
I'll push a PR with the celery icon, today (UTC +9).

**Comment by mingrammer** [comment]
You can add it to `onprem.queue` category: https://diagrams.mingrammer.com/docs/nodes/onprem#onpremqueue

**Comment by gabriel-tessier** [comment]
@thedrow 
Thanks for +1 this issue and for Celery, the PR was merged.

@mingrammer 
Thank you for the merge.
