### ISSUE TITLE
Misaligned Node Labels

### ISSUE THREAD

**Issue by bkmeneguello** [mingrammer/diagrams#7]
By the way, excellent project!

I've run the examples but the node labels are bad aligned. Maybe I'm using some incompatible graphviz version

* graphviz: 2.40.1-2
* diagrams: 0.2.1

![clustered_web_services](https://user-images.githubusercontent.com/1322552/74231007-50132180-4ca4-11ea-89f7-b2f17872e094.png)

**Comment by mingrammer** [comment]
Would you please try with `graphviz version 2.43.0 (0)`?

**Comment by isaacanthony** [comment]
I encountered the same bug. The current stable version of graphviz is 2.42.3. Is there a way we could make diagrams' label rendering backwards-compatible with earlier versions of graphviz? I'm using graphviz v2.38.0.

**Comment by mingrammer** [comment]
@isaacanthony diagrams v0.2.2 now released. Could you please test with v0.2.2 :)? (changes: increase node height)

**Comment by bkmeneguello** [comment]
v0.2.2 still not solved, but improved a little in the right direction ;). I'll try with new graphviz.
![clustered_web_services](https://user-images.githubusercontent.com/1322552/74254410-2d4a3280-4ccf-11ea-9466-3c4158ed5c7b.png)

**Comment by isaacanthony** [comment]
I am still seeing the issue as well on graphviz v2.38.0.

**Comment by juanspinelli** [comment]
In windows I have the same problem but now with v0.2.2 the labels look better (before they looked above)   [https://ibb.co/0yjSh1k](url)

**Comment by bkmeneguello** [comment]
The current stable vesion of graphviz is 2.40.1 (https://graphviz.gitlab.io/_pages/Download/Download_source.html) and I'm not able to use a newer version because of missing dependencies. I need to stick to 2.40.1 by now (maybe I can try with docker sooner)

**Comment by DylanSp** [comment]
Love the project! But I have the same issue with graphviz 2.38, which is what the [graphviz install page](https://graphviz.gitlab.io/download/) points to as stable installs for Windows.

**Comment by mingrammer** [comment]
I found a root cause. Please next release!

**Comment by mingrammer** [comment]
diagrams v0.2.3 is now released. Please check with this version.

cc @bkmeneguello @isaacanthony @juanspinelli @DylanSp 

> `imagepos` attribute is available `graphviz >= 2.42.0`.

**Comment by juanspinelli** [comment]
Now it looks awesome thanks! https://ibb.co/k011ppr

**Comment by DylanSp** [comment]
Definitely looks better even with Graphvis 2.38. Thanks for the quick response on this!

**Comment by isaacanthony** [comment]
It is fixed. Thanks! Even a little more padding would probably be welcome, but a major improvement. Thank you for your quick response.

**Comment by bkmeneguello** [comment]
It's definitely fixed. Thanks a lot. I never saw a fastest maintainer!
