### ISSUE TITLE
unable to draw Linked Clusters 

### ISSUE THREAD

**Issue by mxw-sec** [mingrammer/diagrams#707]
In my diagram I am trying to create a Clustered Web app Diagram.  This Diagram is Edge to multiple nested Clusters..

 dns(edge) >> fw_group (cluster1) >> f5_group(cluster2) >> webapp(cluster3) ...... final resource..  However when I create the diagram if I try to graph cluster to cluster I get an error. TypeError: unsupported operand type(s) for >>: 'list' and 'list', if I setup a single point in between it works just fine.. 

Code Snippet:

`from diagrams import Cluster, Diagram
from diagrams.aws.compute import ECS
from diagrams.aws.database import RDS
from diagrams.aws.network import ELB
from diagrams.aws.general import GenericFirewall
from diagrams.aws.network import Route53

with Diagram("Trial Webapp", show=False):

    dns = Route53("dns")
    lb = ELB("F5LB01")
    
    with Cluster("Firewalls"):
        fw_group = [GenericFirewall("FWCP1"),
                    GenericFirewall("FWCP2"),
                    GenericFirewall("FWCP3")] 

    with Cluster("F5 Load Balancers"):
        f5_group = [ELB("f5lb01"),
                    ELB("f5lb02"),
                    ELB("f5lb03")]

    with Cluster("Onboarding"):
        webapp = [ECS("WEB8"),
                  ECS("WEB10"),
                  ECS("WEB11"),
                  ECS("WEB08"),
                  ECS("WEB18"),
                  ECS("WEB19")]

    dns >> fw_group >> lb >> webapp` <-- This works

**dns >> fw_group >>f5_group >> webapp  <-- this does not work..**

**Comment by RyanMillerC** [comment]
Linking two *Clusters* together isn't supported (would be awesome).

What you're trying to do is link two lists of *Nodes* together. You can take a single Node and `>>` to a list of Nodes. You can't take a list of Nodes and `>>` into another list of Nodes.

What you can do instead loop through the first list:

```
from diagrams import Cluster, Diagram, Edge

from diagrams.k8s.compute import Deployment, Pod

with Diagram("Diagram", show=False):
    app_1_pods = [
        Pod('App 1'),
        Pod('App 1'),
        Pod('App 1')
    ]

    app_2_pods = [
        Pod('App 2'),
        Pod('App 2'),
        Pod('App 2')
    ]

    for pod in app_1_pods:
        pod >> app_2_pods
```

Warning: this is messy...

![image](https://user-images.githubusercontent.com/5067109/173411737-b3a02230-15e7-4f90-9c38-d934651fc469.png)

Setting `splines` to `line` makes it slightly better but still messy:

```python
from diagrams import Cluster, Diagram, Edge

from diagrams.k8s.compute import Deployment, Pod

graph_attr = {
    "splines": "line"
}

with Diagram("Diagram", show=False, graph_attr=graph_attr):
    app_1_pods = [
        Pod('App 1'),
        Pod('App 1'),
        Pod('App 1')
    ]

    app_2_pods = [
        Pod('App 2'),
        Pod('App 2'),
        Pod('App 2')
    ]

    for pod in app_1_pods:
        pod >> app_2_pods
```

![image](https://user-images.githubusercontent.com/5067109/173412089-739918bd-8ad3-4d5e-be5f-696089d53187.png)

**Comment by clayms** [comment]
See the issue comment below for solutions to "link" clusters.
https://github.com/mingrammer/diagrams/issues/17#issuecomment-723564748

**Comment by mxw-esi** [comment]
@RyanMillerC Thanks for the information. I did find #17 later after my post, but I had hoped there was a better way to natively map the clusters versus the "splines:lines" it would be easier to treat the "cluster" item as if it was a single entity with an external edge connection point so that you could easily map cluster to cluster versus the requirement to map node to node. 

Thanks for the response. this will drastically improve our technical diagram capabilities once we find a way to natively update the file from our CI/CD Process.

Does the diagram code support nested configuration ingest? 

For example for Application 1

with Diagram("Diagram", show=False, graph_attr=graph_attr):
    app_1_pods = [
        Pod('App 1'),
        Pod('App 1'),
        Pod('App 1')
    ]

    app_2_pods = [
        Pod('App 2'),
        Pod('App 2'),
        Pod('App 2')
    ]

    for pod in app_1_pods:
        pod >> app_2_pods
    
    then every time i need to connect to app1 and its dependencies, I just reference the source python file as an include?
    
    so my next app might be 
    
    Front End.py
from app1.py import app1

with Diagram("Front-end to App1", show=False, graph_attr=graph_attr):
    frontend =FD()

frontend >> app1

**Comment by RyanMillerC** [comment]
I wasn't aware of that workaround. Good to know. 😃

@mxw-esi I tried what you're suggesting and got `OSError: Global diagrams context not set up`. There might be a way to make it work but I've never used diagrams that way.

(p.s. if you wrap your code with a ``` on a line by itself at the beginning and end of the code block, GitHub will format it)
