### ISSUE TITLE
Is diagrams still maintained?

### ISSUE THREAD

**Issue by DataDavD** [mingrammer/diagrams#723]
Is diagrams maintained anymore?

No releases since early February. Lots of existing, PRs still open...
😢 😕

**Comment by pablodz** [comment]
time to fork? 

![image](https://user-images.githubusercontent.com/28235457/177242522-a589d78d-5633-44dd-aa5e-4b4b6239d602.png)

**Comment by mingrammer** [comment]
I was busy these days. I'm willing to review the pending PRs and do maintaining it again soon.

**Comment by pablodz** [comment]
Thanks for all @mingrammer , your library is really helpful

**Comment by askpatrickw** [comment]
It always hard when one person makes something cool and everyone rushes in.
Are there other Contributors who can help with the maintenance process, reviews, etc.?

I contribute to CircuitPython and one thing they do which works well, is they have a lot of people who can review PRs, leave feedback, etc even when they limit who can merge. It frees up the core devs from having to do _everything_. Might be something to consider.

**Comment by DataDavD** [comment]
Thanks @mingrammer no worries at all. I know we all completely understand. I'm happy to assist in the manner suggested by @askpatrickw if it helps. I'm limited on time though which is why it'd be hard to dev much, but happy to help review stuff here and there to assist u.

Thank you very much for using your valuable time to help us all with suggest a great library. 🙏🙏🙏🙏🙏🙏🙏🙏🙏

**Comment by DataDavD** [comment]
closing this ticket :)
