### ISSUE TITLE
Impossible to import

### ISSUE THREAD

**Issue by DRAKUN** [mingrammer/diagrams#75]
ImportError: cannot import name 'Diagram' from partially initialized module 'diagrams'

prp diagrams.py                                                                                                                           ─╯
Traceback (most recent call last):
  File "diagrams.py", line 2, in <module>
    from diagrams import diagram
  File "/Users/daman/MISSION/M-ALTAVIA/ALTAVIA/iac/all_cluster/archi/diagrams.py", line 2, in <module>
    from diagrams import diagram
ImportError: cannot import name 'diagram' from partially initialized module 'diagrams' (most likely due to a circular import) (/archi/diagrams.py)

i used pipenv

**Comment by pchaganti** [comment]
Might be because you named your script diagrams.py, which is the same name as the module you are importing?

**Comment by DRAKUN** [comment]
Oh Damn

**Comment by mingrammer** [comment]
Can I close it?

**Comment by DRAKUN** [comment]
Yeah I’m okay

DaMaN DiaWarA

Le 24 mars 2020 à 03:35, MinJae Kwon <notifications@github.com> a écrit :

﻿

Can I close it?

**Comment by kubukoz** [comment]
LOL. As a non-python person hitting this issue I'm not shocked at all that I didn't even consider the filename 😅
