### ISSUE TITLE
Include full AWS asset package of icons

### ISSUE THREAD

**Issue by jpreszler** [mingrammer/diagrams#764]
There are a lot of AWS icons missing. Could the entire icon asset package at https://aws.amazon.com/architecture/icons/ be included?

**Comment by mingrammer** [comment]
I'll update it soon. Thank you for informing us.

**Comment by bdsoha** [comment]
@jpreszler This is `~60Mb` of images alone.

**Comment by gabriel-tessier** [comment]
@mingrammer 
I can check and add the missing icons if you want.

@bdsoha  60 Mb it's the size of the zip file (uncompressed is 63Mb), but inside there's different size, theme and format of the same file as written above the link.

> Package contains sets for both dark and light backgrounds in both PNG and SVG file formats.

But I think that @bdsoha raise a concern about the size of the resource directory and by extension the lib file. The more provider and icons are added the more the file will become heavy. On master the resources directory is 24Mb not yet big but we may start to think about alternative idea before reaching 100Mb.
We can talk about in discuss or in another issue. So far I thought about 2 alternatives:
- You can create a different project something like diagrams-custom-resources that will only accept icons and can be called with Custom node and the url hosted by Github! 
- Have diagrams with basic provider [programming, onprem etc...] and AWS, IBM etc... as dependencies that can be handled by setuptools.
https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#optional-dependencies

**Comment by bdsoha** [comment]
@gabriel-tessier I mentioned some of those options [here](https://github.com/mingrammer/diagrams/issues/176#issuecomment-1308243386), in regard to optimizations.

**Comment by gabriel-tessier** [comment]
Thanks for the link I mess this issue sorry for the noise.

**Comment by bdsoha** [comment]
@gabriel-tessier It would be great to record your ideas on that issue.

**Comment by karim-soufi** [comment]
Hello,

Any updates regarding this issue?
one of the missing icons is ECS Task Definition wich is a very popular service.
