### ISSUE TITLE
Make icons more visible in the docs

### ISSUE THREAD

**Issue by yu-iskw** [mingrammer/diagrams#78]
## Motivation
We already have the documentations about the nodes. Those would help us knowing what products we can use. Meanwhile, they can get better by showing the icon images. What if we can see the icon images on the docs?

## Suggestion
We probably have the two options to make the icon images visible on the docs.
1. We create new pages or markdown files for lists of the icons.
2. We show an icon image when hovering the node.

The second options looks like the following. When hovering a node, the icon image is popped up.
![2020-03-24_diagram-suggestion](https://user-images.githubusercontent.com/1523515/77395710-82588880-6de5-11ea-8a43-539e550e976b.png)

**Comment by mingrammer** [comment]
Great ideas. I prefer the first option. I'll do work for it.

Thank you.
