### ISSUE TITLE
bug: Text on "Flask" icon overlaps label

### ISSUE THREAD

**Issue by ewinnington** [mingrammer/diagrams#794]
The Flask icon, when used in a diagram, has the text "Flask", which overlaps the label. 

I guess it is because the icon is too tall (256x382 px).   

![deployed_jobs](https://user-images.githubusercontent.com/3533203/201368689-ecaaacae-250d-4af0-8e28-3570115cf94a.png)

```python
from diagrams import Diagram
from diagrams.programming.framework import Flask
from diagrams.onprem.client import Users
from diagrams.programming.language import Python
from diagrams.onprem.workflow import Airflow

with Diagram("Deployed jobs"):
    Users("End user") >> Flask("website")
    Airflow("Task") >> Python("Import Function")
```

**Comment by leirons** [comment]
Tested and seems fine with this icon, can you create pull request?

**Comment by bdsoha** [comment]
@mingrammer  @ewinnington This can be closed.

**Comment by mingrammer** [comment]
I close it.
