### ISSUE TITLE
Black is in base dependencies

### ISSUE THREAD

**Issue by sveetch** [mingrammer/diagrams#803]
Hi,

From current pyproject.toml i'm seeing that Black is a base dependency for package install. I have seen it was previously a "dev-dependencies" then  it have been moved to the base.

I didn't read the whole documentation yet but from what i've digged i didn't see anything that would require Black for diagrams to work correctly.

Did i miss something about it ?

Thanks.

**Comment by mingrammer** [comment]
Hi @sveetch. You are right. black is not a required module for diagrams. It was my mistake. I fixed it with 18a1976. Thank you for raising this issue!! ❤️
