### ISSUE TITLE
Label of edge misaligned

### ISSUE THREAD

**Issue by tducret** [mingrammer/diagrams#83]
Hi there,
Firstly, I love this project, thanks a lot!
I am currently trying to create a diagram with labelled edges but the label position is incorrect.

For example, when building [this example from the doc](https://diagrams.mingrammer.com/docs/getting-started/examples#advanced-web-service-with-on-premise-with-colors-and-labels).
You can compare the position of label **collect** (on the right of the image, between metric and replica) with the one of the documentation (which seems correct).

Tested with :
- Ubuntu 18.04 and dot - graphviz version 2.40.1 (20161225.0304)
- Ubuntu 20.04 and dot - graphviz version 2.43.0 (0)

In both configurations, here is what I get:
![advanced_web_service_with_on-premise_(colored)](https://user-images.githubusercontent.com/2735014/77778018-a8359580-7050-11ea-8d6c-0a0790b44317.png)

Image from the documentation:
![image](https://user-images.githubusercontent.com/2735014/77778574-7f61d000-7051-11ea-81c6-4aaf6ad7c541.png)

Any clue?

**Comment by jagregory** [comment]
Seeing the same issue here on OSX and graphviz 2.42.3

**Comment by mingrammer** [comment]
I'll check and try to fix it :) thanks for reporting it.

**Comment by xiaoqingsai** [comment]
Seeing the same issue here on Windows10 and graphviz 2.38.

**Comment by mingrammer** [comment]
@xiaoqingsai A contributor who made the `Edge` class used the `label` at a first PR. But I requested the change that modifies the `label` to `xlabel` due to the same error you've seen.

When we use the `label` with `splines=orthogonal`, labels of lines bent at right angles are displayed incorrectly like this (and with the error message, but I think we can ignore this error):

<img width="242" alt="Screen Shot 2020-05-14 at 7 32 21 PM" src="https://user-images.githubusercontent.com/6178510/81924291-e5161580-9619-11ea-92f1-bf99373d0a29.png">

Another option is to use `curved` instead of `orthogonal`, with this, the diagrams will be rendered like this:

<img width="549" alt="Screen Shot 2020-05-14 at 7 37 47 PM" src="https://user-images.githubusercontent.com/6178510/81924759-7dac9580-961a-11ea-801d-1fca5ca58d6b.png">

In this case, all the labels look good regardless of the shapes of the lines.

So we have two options.

1. orthogonal + label + ignore some misaligned labels for lines have right angles.
2. curved + label

**Comment by mingrammer** [comment]
@tducret @jagregory @xiaoqingsai

Which option do you prefer? Of course, I can support both options and use only `label` instead of `xlabel`.

**Comment by tducret** [comment]
Thanks for the investigation @mingrammer 
I'm not sure I understand properly.
If you support both orthogonal and curved, does the initial bug remain, or is it just the problem of right angles?

**Comment by mingrammer** [comment]
The initial bug you reported will be fixed, but the new problem of right angles will be remained.

**Comment by tducret** [comment]
Alright thanks. I think the right angle problem is acceptable.

**Comment by mingrammer** [comment]
Great. I'll fix this issue with the above solution, and will let you know when done.

**Comment by tducret** [comment]
Thanks!

**Comment by davepmarshall** [comment]
> I fixed it by modifying 'xlabel' to 'label'. But dot has a warning
> 
> > Warning: Orthogonal edges do not currently handle edge labels. Try using xlabels.
> 
> I'm not familiar with Graphviz, so I don't know if there's any other impact.

Oddly, changing to xlabel doesn't fix it for me. Any ideas how I can work around this?

**Comment by mingrammer** [comment]
Pin this issue. WIll be resolved in a week.

**Comment by mingrammer** [comment]
Please try with diagrams@0.15.0!

**Comment by tducret** [comment]
Tested with 0.15.0 👍 
Thank you very much!
![advanced_web_service_with_on-premise_(colored)](https://user-images.githubusercontent.com/2735014/85953977-76e0a480-b974-11ea-92b8-c654d13b1fc1.png)

**Comment by mingrammer** [comment]
Great! :)

**Comment by mvsoliveira** [comment]
Hi, I am getting the labels not very well aligned to the Arrows (Edge). 
Can you please point me in the direction to solve it?
 
dot - graphviz version 2.50.0 (20211204.2007)
python packages:
diagrams 0.23.1
graphviz 0.20.1
[latome_real-time_path_block_diagram.pdf](https://github.com/mingrammer/diagrams/files/10145134/latome_real-time_path_block_diagram.pdf)



```
from diagrams import Diagram, Edge, Cluster
from diagrams.c4 import C4Node
from functools import partial
block = partial(C4Node, type='')
conne = partial(Edge, splines='curved')

efex_enc=16
jfex_spn=32
jfex_enc=16
flat = False

if flat:
    ids = range(efex_enc)
    jids = range(jfex_enc)
    di = {i : f'{i}' for i in range(efex_enc)}
    dr = {i : f'{i * 20}:{(i + 1) * 20 - 1}' for i in range(efex_enc)}
    jdi = {i: f'{i}' for i in range(jfex_spn)}
    jdr = {i: f'{i * 16}:{(i + 1) * 16 - 1}' for i in range(jfex_enc)}
else:
    ids = [0, 1, 2, 15]
    di = {i : f'{i}' if i !=2 else '(...)' for i in range(efex_enc)}
    dr = {i : f'{i * 20}:{(i + 1) * 20 - 1}' if i !=2 else '(...)' for i in range(efex_enc)}
    jids = [0, 1, 2, 31]
    jdi = {i: f'{i}' if i != 2 else '(...)' for i in range(jfex_spn)}
    jdr = {i: f'{i * 16}:{(i + 1) * 16 - 1}' if i != 2 else '(...)' for i in range(jfex_enc)}


with Diagram("LATOME real-time path block diagram", show=False, direction='LR',outformat="pdf"):
    lli_rx = block('Rx')
    lli_tx = block('Tx')
    istage = block('Istage')
    ser = block('Serializer')
    with Cluster("Remap"):
        ism = block("Input Switch matrix")
    user = block("User")
    #mon = block("Mon/TDAQ")

    with Cluster("Osum"):
        adapter = block("EMEC adapter")
        masking = block("Masking")
        osm = block("Output Switch Matrix")
        with Cluster("eFEX"):
            efexmle = block('MLE')
            efex_mle = [0]*efex_enc
            efex_crc = [0]*efex_enc
            efex_frb = [0]*efex_enc
            for i in range(efex_enc):
                if i in ids:
                    with Cluster(f'eFEX encoder {di[i]}'):
                        efex_crc[i] = block(f"CRC {di[i]}")
                        efex_frb[i] = block(f"Frame builder {di[i]}")
                    efexmle >> conne(forward=True,label=f'{dr[i]}') >> efex_crc[i]
                    efex_crc[i] >> conne(label="20 & CRC") >> efex_frb[i]
        with Cluster("jFEX"):
            jfexssm = block('Sum Switch Matrix')
            jfexism = block('Input Switch Matrix')
            jfexmle = block('MLE')
            jfex_sum = [0]*jfex_spn
            jfex_crc = [0]*jfex_enc
            jfex_frb = [0]*jfex_enc
            for i in range(jfex_spn):
                with Cluster(f'jFEX sum'):
                    if i in jids:
                        jfex_sum[i] = block(f"SUM {jdi[i]}")
                        jfexssm >> conne(label='10') >> jfex_sum[i] >> conne(label="1") >> jfexmle
            jfexism >> conne(label='224') >> jfexmle
            for i in range(jfex_enc):
                if i in ids:
                    with Cluster(f'jFEX encoder {di[i]}'):
                        jfex_crc[i] = block(f"CRC {i}")
                        jfex_frb[i] = block(f"Frame Builder {i}")
                        jfexmle >> conne(forward=True,label=f'{jdr[i]}') >> jfex_crc[i] >> conne(label="16 & CRC") >> jfex_frb[i]


    lli_rx >> conne(label="48x8 words",style='dashed') >> istage >> conne(label="384") >> ism >> conne(label="320") >> user >> conne(label="320") >> adapter >> conne(label="320") >> masking >> conne(label="320") >> efexmle
    masking >>  conne(label="320") >> jfexism
    masking >> conne(label="320") >> jfexssm
    osm >> conne(label="48 frames",style='dashed') >> ser >> conne(label="48x7 words",style='dashed') >> lli_tx

    for i in range(efex_enc):
        if i in ids:
            efex_frb[i] >>  conne(label="1") >> osm
    for i in range(jfex_enc):
        if i in ids:
            jfex_frb[i] >>  conne(label="1") >> osm

```

**Comment by hmustufa-n** [comment]
I'm seeing a similar issue; could we add an Edge parameter that specifies alignment (maybe top, center, bottom, horizontal) where horizontal aligns with the horizontal portion of an orthogonal edge?
