### ISSUE TITLE
Add slack

### ISSUE THREAD

**Issue by yu-iskw** [mingrammer/diagrams#89]
## Motivation
We sometimes do chatops with slack. We can potentially regard slack as a part of cloud architecture. So, it would be great to add the slack icon.

## Resources
https://brandfolder.com/slack/logos

## Comment
If it would be ok to add slack, I am not sure where it should be categorized.

**Comment by mingrammer** [comment]
I agree with you. And we can use the Slack as notification component as well.

**Comment by mingrammer** [comment]
I'm thinking about which category is appropriate for Slack .. 🤔 Any ideas?

**Comment by taylorreece** [comment]
Would it make sense to have a `diagrams.onprem.social` category, and throw in Slack, IRC, Microsoft Teams, Skype, Facebook, Twitter, etc?

**Comment by mingrammer** [comment]
`social` is not bad. I like it. How about it? @yu-iskw

**Comment by yu-iskw** [comment]
`social` is not bad to me too. Personally, I prefer `communication`, but it is a little long as a namespace.

Another discussion is whether or not we can use `diagrams.onprem`, because we cannot use slack on onpremis environmenst at the moment.

**Comment by mingrammer** [comment]
Ye we should discuss about that. I think the Slack, MS teams, Twitter and others mentioned above might not be fit to `diagrams.onprem`. So I propose a new provider, the `saas`. Then we can categorize them into more detailed like this:

- diagrams.saas.social.Facebook
- diagrams.saas.social.Twitter
- diagrams.saas.messenger.Slack (or chat.Slack)
- diagrams.saas.messenger.Telegram (or chat.Telegram)
...

Any thoughts?

**Comment by taylorreece** [comment]
> Ye we should discuss about that. I think the Slack, MS teams, Twitter and others mentioned above might not be fit to `diagrams.onprem` provider. So I propose a new provider, the `saas`. Then we can categorize them in more detail like this:
> 
> - diagrams.saas.social.Facebook
> - diagrams.saas.social.Twitter
> - diagrams.saas.messenger.Slack (or chat.Slack)
> - diagrams.saas.messenger.Telegram (or chat.Telegram)
> ...
> 
> Any thoughts?

I really like that proposal

**Comment by yu-iskw** [comment]
@mingrammer I love your proposal.

**Comment by dhirschfeld** [comment]
I'll put in a plug for [zulip](https://zulipchat.com/); though happy to try adding it myself if there's a good location to put it.

**Comment by mingrammer** [comment]
@gabriel-tessier is working on it.

**Comment by mingrammer** [comment]
It will be added in the next version.
