### ISSUE TITLE
Support having generic text on the diagram

### ISSUE THREAD

**Issue by fawaf** [mingrammer/diagrams#930]
for example, a small blurb describing what the diagram is about at either the top or bottom of the image

**Comment by yolabingo** [comment]
The Diagram `name` parameter provides this as long as you provide a shorter `filename`:

```python
from diagrams import Cluster, Diagram
from diagrams.onprem.container import Docker

description = """
These are servers.

Lorem ipsum dolor sit amet, consectetur adipiscing elit.
Ut quis nisi elementum, accumsan risus ut, convallis justo.
Vestibulum vel suscipit nulla."""

with Diagram(
        name=description,
        filename="docker-diagram",
    ):
    Docker("Docker")
```
![docker-diagram](https://github.com/mingrammer/diagrams/assets/628954/534ef85d-bba0-428e-b5ae-832abd00bca6)

**Comment by fawaf** [comment]
ohh, thanks!
