### ISSUE TITLE
Gitpitch no longer active

### ISSUE THREAD

**Issue by anjaneshbabu** [mingrammer/diagrams#941]
https://gitpitch.github.io/gitpitch/#/free-trial

"GitPitch is shutting down on March 1, 2021. The trial software is no longer available for download."
Domain not active anymore.
Please remove references to Gitpitch. from "Who uses it "
https://github.com/mingrammer/diagrams#who-uses-it

**Comment by mingrammer** [comment]
I removed it. Thank you.
