### ISSUE TITLE
How do I remove white space from around the image?

### ISSUE THREAD

**Issue by mcleantom** [mingrammer/diagrams#949]
I am generating an image like this:

```python
from .common import OUTPUT_DIR
from diagrams import Diagram
from diagrams.aws.compute import Lambda
from diagrams.aws.network import APIGateway
from diagrams.aws.network import Route53

output_file = OUTPUT_DIR / "routing_server"
with Diagram(show=False, filename=str(output_file), outformat=["png"]):
    Route53("routing.bar-tech.uk") >> APIGateway("API Gateway") >> Lambda("Routing Server")
```

and the image looks like:
![image](https://github.com/mingrammer/diagrams/assets/64887735/e80b5e3b-5a99-43c5-8684-c0cbcb10ec6c)

Is there any way to remove the white space surrounding the image?

**Comment by shekharskamble** [comment]
Looking for a solution for this as well

**Comment by clayms** [comment]
https://github.com/mingrammer/diagrams/issues/459#issuecomment-774560588

**Comment by shekharskamble** [comment]
@clayms works perfectly, thanks a lot guys for super quick response
