### ISSUE TITLE
ImportError: cannot import name 'Diagram' from partially initialized module 'diagrams'

### ISSUE THREAD

**Issue by gingerbeard72** [mingrammer/diagrams#954]
Following the installation guide to test diagram. Running this on ubuntu (WSL) using Python 3.12  (also tried Python 3.9). Using the example diagram code on the installation page and I am getting this response;

python3 testdrawing.py
Traceback (most recent call last):
  File "/home/mark/testdrawing.py", line 1, in <module>
    from diagrams import Diagram
  File "/home/mark/diagrams.py", line 1, in <module>
    from diagrams import Diagram
ImportError: cannot import name 'Diagram' from partially initialized module 'diagrams' (most likely due to a circular import) (/home/mark/diagrams.py)

diagram and associated dependencies appear to be installed;
python3 -m pip install diagrams
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: diagrams in /home/mark/.local/lib/python3.10/site-packages (0.23.4)
Requirement already satisfied: graphviz<0.21.0,>=0.13.2 in /home/mark/.local/lib/python3.10/site-packages (from diagrams) (0.20.1)
Requirement already satisfied: jinja2<4.0,>=2.10 in /home/mark/.local/lib/python3.10/site-packages (from diagrams) (3.1.2)
Requirement already satisfied: typed-ast<2.0.0,>=1.5.4 in /usr/local/lib/python3.10/dist-packages (from diagrams) (1.5.5)
Requirement already satisfied: MarkupSafe>=2.0 in /home/mark/.local/lib/python3.10/site-packages (from jinja2<4.0,>=2.10->diagrams) (2.1.1)

The file is not named diagram.py but testdrawing.py

I have read over some of the other issues and all issues appear to be related to the file name or diagrams not having been installed but I feel that my issue is different.

Any assistance is greatly appreciated

**Comment by alanthssss** [comment]
@gingerbeard72 
Hi, Mark, Nice to ping. Kind to see the details, it's important for debug.

Maybe we could try 2 points only for the name of `.py` files:
- Rename or movethe `/home/mark/diagrams.py`, it's in the same folder of `/home/mark/testdrawing.py`, so it has a high priority than the real module `diagrams` which we installed. It's the reason's `circular import`  
- Rename our business `.py` file which has `test` prefix, it also has risk of the `.py` programming's executable, it's a format for test task instead of usual business task.
- 
Feel free to ping again, Cheers

**Comment by gingerbeard72** [comment]
Thanks for this information. I only followed the first point and the command completed successfully.

I will do the change recommended in your second point now. I feel that this can be closed

**Comment by alanthssss** [comment]
> Thanks for this information. I only followed the first point and the command completed successfully.
> 
> I will do the change recommended in your second point now. I feel that this can be closed

My pleasure!
Glad to see your feedback.
Cheers!
