### ISSUE TITLE
Python 3.12 not supported

### ISSUE THREAD

**Issue by l4time** [mingrammer/diagrams#966]
Python 3.12 does not seem to be supported as [typed-ast](https://github.com/python/typed_ast/issues/179) library is now EOL and no [wheels package](https://pypi.org/project/typed-ast/#files) exists for python 3.12.

Error message:
` 
ERROR: Failed building wheel for typed-ast
Failed to build typed-ast
ERROR: Could not build wheels for typed-ast, which is required to install pyproject.toml-based projects
`

Is there any way to switch over to the ast library as it is now recommended for Python versions above 3.8

**Comment by tb102122** [comment]
See the relateed suggestion
https://github.com/python/typed_ast/issues/179

**Comment by tb102122** [comment]
PR created
https://github.com/mingrammer/diagrams/pull/972

**Comment by endlesslycurious** [comment]
@gabriel-tessier @filipeaaoliveira Apologies for the tag but saw you made commits recently; any chance we can take a look at this PR to fix installations on python versions 3.12 and ideally 3.13 too?

**Comment by tb102122** [comment]
@endlesslycurious there is no active contribution on the repo. You can submit a PR in the forked repo https://github.com/diagrams-web/diagrams-xtd

**Comment by gabriel-tessier** [comment]
@tb102122
Sorry to not inform you earlier but mingrammer give us collaborator access and we are starting slowly to merge PR and close issues.

More details here:
https://github.com/mingrammer/diagrams/discussions/1015

I postponed the diagrams-ext fork for now, try to focus and improve here.

@mingrammer 
if it's ok to add one more collaborator can you also add @tb102122 he can be really helpful here.

@endlesslycurious 
Thanks for the comment it help for triage and set priorities.

**Comment by tb102122** [comment]
@gabriel-tessier no problem.
@mingrammer happy to help.

**Comment by endlesslycurious** [comment]
That's great news, it seems a useful package that I look forward to trying out!

**Comment by endlesslycurious** [comment]
Speaking of priorities it might be worth putting out a minor version (e.g. `0.23.5`) with _just_ the fix to get the package working with python `3.12` & `3.13` as currently no python version released in the last year works with this package.

**Comment by tb102122** [comment]
@mingrammer @gabriel-tessier should I update the #972 to also include 3.13 support. 3.12 was tested in the fork https://github.com/diagrams-web/diagrams-xtd already.

**Comment by endlesslycurious** [comment]
I see `0.24.0` got released yesterday without the fix for newer python version; anything I can do to help?

**Comment by tb102122** [comment]
I have added the logic for 3.13 as well and resolved the conflicts.

**Comment by mingrammer** [comment]
That PR is merged now. I'll release the new version soon.

**Comment by tb102122** [comment]
@mingrammer the pipeline failed but not sure why
https://github.com/mingrammer/diagrams/actions/runs/11713959003/job/32627728019

**Comment by mingrammer** [comment]
@tb102122 there seems missing double quote:

typed-ast = { version = "^1.5.5", markers = "python_version < '3.8'}

**Comment by tb102122** [comment]
you are right 
https://github.com/mingrammer/diagrams/pull/1050

**Comment by mingrammer** [comment]
[v0.24.1](https://github.com/mingrammer/diagrams/releases/tag/v0.24.1) is now released.

**Comment by endlesslycurious** [comment]
Awesome, confirmed installing successfully for Python `3.13.0` on Mac and `3.11.9` on Windows 11 Pro!
