### ISSUE TITLE
How do you generate diagrams with transparent background?

### ISSUE THREAD

**Issue by flyisland** [mingrammer/diagrams#973]
Diagrams with transparent backgrounds would be more convenient to use in slides, thanks.

**Comment by filipeaaoliveira** [comment]
Hi @flyisland 

You can add a transparent background with the option: `graph_attr={"bgcolor": "transparent"}`

Like this, for example:

`from diagrams import Diagram
from diagrams.aws.compute import EC2
from diagrams.aws.database import RDS
from diagrams.aws.network import ELB

with Diagram(
    "Web Service", show=False, outformat="png", graph_attr={"bgcolor": "transparent"}
):
    ELB("lb") >> EC2("web") >> RDS("db")
`

**Comment by flyisland** [comment]
it works, thanks
