### ISSUE TITLE
Error importing Diagram

### ISSUE THREAD

**Issue by mglzgsr** [mingrammer/diagrams#98]
I have followed the steps in the [installation page](https://diagrams.mingrammer.com/docs/getting-started/installation), but got an error importing Diagram using the example:
```
Traceback (most recent call last):
  File "diagrams.py", line 2, in <module>
    from diagrams import Diagram
  File "/Users/migu8936/Desktop/diagrams.py", line 2, in <module>
    from diagrams import Diagram
ImportError: cannot import name Diagram
```
Not sure if it's needed any configuration more, cannot see any more info.
Any help?
Graphviz - 2.42.3 (installed by brew)
Python - 2.7.16 (MacOS default) and 3.7.7
Diagrams - 0.8.2 (installed using pip3)

**Comment by pchaganti** [comment]
Are you naming your python file diagrams.py? If you do the import will fail as Python will try to import it from the wrong place.

**Comment by mingrammer** [comment]
As @pchaganti mentioned, you shouldn't name the file as `diagrams.py` to use diagrams package.

**Comment by mglzgsr** [comment]
The name is not the problem, I used python3 to run the exact same script and worked. It's compatibility with the default python included with MacOS.
Thank you guys!
