### ISSUE TITLE
Icon Request: Azure Speech To Text , Azure Open AI 

### ISSUE THREAD

**Issue by Chandan-Baba** [mingrammer/diagrams#982]
Hi,

First of all, thanks for this wonderful piece of work. I am really impressed with it and helped in my till date journey.

I am trying to learn[ azure open ai](https://learn.microsoft.com/en-us/azure/architecture/ai-ml/openai/architecture/call-center-openai-analytics) stuff and would like to use mingrammer to showcase the architecture but currently I couldn't able to find my few of example icon support. 

May I request if following Icon support can be provided? or can I know how to add icons I will try to contribute.

- Azure Speech To Text, 
- Azure Open AI 

Thanks again.

**Comment by RaeldZues** [comment]
Have you tried using the Custom node? I find it useful for purposes like these. 

https://diagrams.mingrammer.com/docs/nodes/custom

**Comment by rfernandezdo** [comment]
It would be corrected if the PR was merged https://github.com/mingrammer/diagrams/pull/980
