### ISSUE TITLE
This idea is just too good to just die

### ISSUE THREAD

**Issue by joserocha** [mingrammer/diagrams#995]
Do any of the contributors have any idea what happened? Is it a case of making a fork and continuing with that fork?

**Comment by tb102122** [comment]
Did you get any response from the developer? @joserocha

**Comment by ebbypeter** [comment]
@mingrammer will you consider giving some community members write access / approve pull request access?

**Comment by tb102122** [comment]
happy to support as well

**Comment by gabriel-tessier** [comment]
If you are interested I have a fork that I maintain and try to keep up to date, but so far nobody use (no issue or PR) so it's more a selfish fork.

https://github.com/diagrams-web/diagrams-xtd

It's already an organization so I can quickly add any good will that want to help.

I started the fork to make it work with a minimal web interface, and I still use it, the fork is running without the web parts, but have incompatibility with the current version.

https://github.com/diagrams-web/diagrams-xtd/blob/master/CHANGELOG.md

I have a WIP branch that have the latest 0.23.4 compatible changes I can push and release a new version. As I don' use the latest changes I did not yet push it.
If people need I can push and release.

**Comment by tb102122** [comment]
@gabriel-tessier 

Please add me

**Comment by gabriel-tessier** [comment]
@tb102122 
Sent an invitation!

I also push a PR that was staging on my local with the 0.23.4 latest changes. 
Still need to review and run some batch if people are interested I can make a release, or you can join and do it yourself.

**Comment by ebbypeter** [comment]
Please add me in as well...

**Comment by gabriel-tessier** [comment]
@ebbypeter 

I sent the invitation, you should have write access to repositories if you need anything else please open an issue on the organization side.

**Comment by gabriel-tessier** [comment]
Can close as now the project reboot!

 :rocket:
